# @(#) $Header: K:/BCT_Development/vxWorks/Trima/unit_test/datalog/rcs/makefile.vx 1.1 2003/11/24 23:09:23Z jl11312 Exp jl11312 $
#
# Makefile - makefile for trima system initialization software
#
# $Log: makefile.vx $
# Revision 1.1  2003/11/24 23:09:23Z  jl11312
# Initial revision
# Revision 1.10  2003/05/13 16:46:18Z  jl11312
# - force linkage of all symbols from zlib
# Revision 1.9  2003/05/13 15:50:40Z  jl11312
# - renamed compression library
# Revision 1.8  2003/02/28 22:13:34Z  jl11312
# - added initialization for debug tools (see IT 5915)
# Revision 1.7  2003/02/06 20:39:41  jl11312
# - added zlib to link
# Revision 1.6  2002/10/29 19:37:19  jl11312
# - updated to read cal.dat for touchscreen cal data
# Revision 1.5  2002/09/19 21:28:29  jl11312
# - added sysinit for safety
# Revision 1.4  2002/08/21 15:52:38  jl11312
# - added routines needed for message system initialization
# Revision 1.3  2002/08/15 21:06:45  jl11312
# - updated for new makefile templates
# Revision 1.2  2002/07/19 17:02:50  jl11312
# - corrected comment
# Revision 1.1  2002/07/19 14:55:59  jl11312
# Initial revision
#

ifeq ($(BUILD_TYPE),CLEAN)
.PHONY: all
all: clean
else
.PHONY: all
all: check_opt_change apps
endif

#
# Define include directories needed for apps built in this directory
#
ADDN_INCDIR = -I ../../trima_common -I $(COMDIR)

#
# MAINDIR should be set to the relative path from this makefile directory
# to the base trima project directory.  MAINDIR must use \ (DOS/Windows
# style) directory separators if they are needed.
#
MAINDIR = ..\..
include $(MAINDIR)/makefile.vxc

#
# Define location for Trima libraries
#
LIBDIR = $(MAINDIR)/lib

#
# The following should define all of the source files of each type
# to be compiled for the executable
#
APP_NAME := datalog_test_buffer
datalog_test_buffer_dir = ..\bin
datalog_test_buffer_c_files =
datalog_test_buffer_cxx_files = datalog_test_buffer.cpp
datalog_test_buffer_libs =
include $(MAINDIR)/makefile.process_app

APP_NAME := datalog_test_print
datalog_test_print_dir = ..\bin
datalog_test_print_c_files =
datalog_test_print_cxx_files = datalog_test_print.cpp
datalog_test_print_libs =
include $(MAINDIR)/makefile.process_app

APP_NAME := datalog_test_general
datalog_test_general_dir = ..\bin
datalog_test_general_c_files =
datalog_test_general_cxx_files = datalog_test_general.cpp
datalog_test_general_libs =
include $(MAINDIR)/makefile.process_app

APP_NAME := datalog_test_stream
datalog_test_stream_dir = ..\bin
datalog_test_stream_c_files =
datalog_test_stream_cxx_files = datalog_test_stream.cpp
datalog_test_stream_libs =
include $(MAINDIR)/makefile.process_app

APP_NAME := datalog_test_periodic
datalog_test_periodic_dir = ..\bin
datalog_test_periodic_c_files =
datalog_test_periodic_cxx_files = datalog_test_periodic.cpp
datalog_test_periodic_libs =
include $(MAINDIR)/makefile.process_app

apps : $(APP_LIST)

#
# This is the standard makefile for Trima applications
#
include $(MAINDIR)/makefile.build_apps

