#ifndef __ALARMS_H_
#define __ALARMS_H_

enum ALARM_VALUES
{
NULL_ALARM, 
SOUNDS_DAT_BAD_FILE,
SOUNDS_DAT_CRC_CHECK_FAILURE,
SOUNDS_DAT_VALUE_NOT_FOUND,
SOUNDS_DAT_VALUE_OUT_OF_RANGE,
SOUNDS_DAT_PARSE_ERROR
};
#endif 
