# @(#) $Header$
#
# Makefile.rules - common makefile rules for vxWorks
#
# $Log$
#
# This file simply includes the common makefile.rules.  If Trima
# specific modifications are later needed, they can be put here.
#

include $(COMDIR)/makefile.rules

