# @(#) $Header$
#
# $Log$
#
# This file simply includes the common makefile.build_apps.  If Trima
# specific modifications are later needed, they can be put here.
#

include $(COMDIR)/makefile.build_apps

