//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelFormater.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExcelFormater.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap back_32x32 {
            get {
                object obj = ResourceManager.GetObject("back_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;Windows-1252&quot;?&gt;
        ///&lt;FormaterSerialize xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///	&lt;FormaterSettings&gt;
        ///		&lt;HideDefaultSheets&gt;true&lt;/HideDefaultSheets&gt;
        ///	&lt;/FormaterSettings&gt;
        ///	&lt;DatalogColumns&gt;
        ///		&lt;string&gt;File&lt;/string&gt;
        ///		&lt;string&gt;LevelName&lt;/string&gt;
        ///		&lt;string&gt;Line&lt;/string&gt;
        ///		&lt;string&gt;Message&lt;/string&gt;
        ///		&lt;string&gt;NodeID&lt;/string&gt;
        ///		&lt;string&gt;TaskID&lt;/string&gt;
        ///		&lt;string&gt;TaskName&lt;/string&gt;
        ///	&lt;/DatalogColumns&gt;
        ///	&lt;ColumnLists&gt;
        ///		&lt;Column [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap down_32x32 {
            get {
                object obj = ResourceManager.GetObject("down_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap format_48x48 {
            get {
                object obj = ResourceManager.GetObject("format_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap manage_48x48 {
            get {
                object obj = ResourceManager.GetObject("manage_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap next_32x32 {
            get {
                object obj = ResourceManager.GetObject("next_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;customUI xmlns=&quot;http://schemas.microsoft.com/office/2006/01/customui&quot; xmlns:x=&quot;CaridianBCT&quot; onLoad=&quot;RibbonLoaded&quot; loadImage=&quot;GetImage&quot;&gt;
        ///	&lt;ribbon&gt;
        ///		&lt;tabs&gt;
        ///			&lt;tab idQ=&quot;x:Analysis&quot; label=&quot;Analysis&quot;&gt;
        ///				&lt;group id=&quot;DatalogImporter&quot; label=&quot;Datalog Formater&quot;&gt;
        ///					&lt;button id=&quot;FormatButton&quot; label=&quot;Format&quot; image=&quot;format-48x48.png&quot; size=&quot;large&quot; onAction=&quot;FormatDatalog&quot; /&gt;
        ///					&lt;button id=&quot;ManagerButton&quot; label=&quot;Manager&quot; image=&quot;manage-48x48.png&quot; size=&quot;large&quot; onAction=&quot;FormatManager&quot; /&gt;
        ///					&lt;button id=&quot;SettingsButt [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Ribbon {
            get {
                return ResourceManager.GetString("Ribbon", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap settings_48x48 {
            get {
                object obj = ResourceManager.GetObject("settings_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap up_32x32 {
            get {
                object obj = ResourceManager.GetObject("up_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
