/*****************************************************************************\
**
** ExcellAddin.c
**
** Provides the addin registration.
**
\*****************************************************************************/

#ifndef EXCELADDIN_H
#define EXCELADDIN_H

/* Constants *****************************************************************/

static const LPWSTR kFunctionList[][10] = {
{ L"Predict_64_Get_RBCState",                       L"JJ",  L"Predict_64_Get_RBCState",                       L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_RBCDoubleState",                 L"JJ",  L"Predict_64_Get_RBCDoubleState",                 L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_VinTarget",                      L"BJ",  L"Predict_64_Get_VinTarget",                      L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_VinPIRStart",                    L"BJ",  L"Predict_64_Get_VinPIRStart",                    L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_YdchPIR",                        L"BJ",  L"Predict_64_Get_YdchPIR",                        L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_PIRLockin",                      L"BJ",  L"Predict_64_Get_PIRLockin",                      L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_totalPurges",                    L"BJ",  L"Predict_64_Get_totalPurges",                    L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_PIRRequired",                    L"JJ",  L"Predict_64_Get_PIRRequired",                    L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_doingPTFDouble",                 L"AJ",  L"Predict_64_Get_doingPTFDouble",                 L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_secondPartofPTFDouble",          L"AJ",  L"Predict_64_Get_secondPartofPTFDouble",          L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_NumOfSubstates",                 L"JJ",  L"Predict_64_Get_NumOfSubstates",                 L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_ExtracorporealVolume",           L"BJ",  L"Predict_64_Get_ExtracorporealVolume",           L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_ResidualRBCVolume",              L"BJ",  L"Predict_64_Get_ResidualRBCVolume",              L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_PrimeDuration",                  L"BJ",  L"Predict_64_Get_PrimeDuration",                  L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_VinPrime",                       L"BJ",  L"Predict_64_Get_VinPrime",                       L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_numOfTimes",                     L"JJ",  L"Predict_64_Get_numOfTimes",                     L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_convergenceCtr",                 L"JJ",  L"Predict_64_Get_convergenceCtr",                 L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_ProcedureNumber",                L"JJ",  L"Predict_64_Get_ProcedureNumber",                L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_Designator",                     L"JJ",  L"Predict_64_Get_Designator",                     L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_ProcAMAPorMC",                   L"JJ",  L"Predict_64_Get_ProcAMAPorMC",                   L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_ProcBloodType",                  L"JJ",  L"Predict_64_Get_ProcBloodType",                  L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_ProcCollectPlasma",              L"AJ",  L"Predict_64_Get_ProcCollectPlasma",              L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_ProcCollectVolFixed",            L"JJ",  L"Predict_64_Get_ProcCollectVolFixed",            L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_ProcFixedCollectVol",            L"BJ",  L"Predict_64_Get_ProcFixedCollectVol",            L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_ProcFixedPlasmaVol",             L"BJ",  L"Predict_64_Get_ProcFixedPlasmaVol",             L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_ProcPlasmaVolFixed",             L"JJ",  L"Predict_64_Get_ProcPlasmaVolFixed",             L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_ProcPlateletProdCon",            L"BJ",  L"Predict_64_Get_ProcPlateletProdCon",            L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_ProcRBCDose",                    L"BJ",  L"Predict_64_Get_ProcRBCDose",                    L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_ProcRBCHct",                     L"BJ",  L"Predict_64_Get_ProcRBCHct",                     L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_ProcRBCVolume",                  L"BJ",  L"Predict_64_Get_ProcRBCVolume",                  L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_ProcPtfIsSplit",                 L"AJ",  L"Predict_64_Get_ProcPtfIsSplit",                 L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_ProcTime",                       L"BJ",  L"Predict_64_Get_ProcTime",                       L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_DesiredYield",                   L"BJ",  L"Predict_64_Get_DesiredYield",                   L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_MSSPlt",                         L"AJ",  L"Predict_64_Get_MSSPlt",                         L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_MSSPltVolume",                   L"JJ",  L"Predict_64_Get_MSSPltVolume",                   L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_MSSPltPctCarryover",             L"JJ",  L"Predict_64_Get_MSSPltPctCarryover",             L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_OriginalPltVolume",              L"BJ",  L"Predict_64_Get_OriginalPltVolume",              L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_OriginalPltYeild",               L"BJ",  L"Predict_64_Get_OriginalPltYeild",               L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_MSSRbc",                         L"AJ",  L"Predict_64_Get_MSSRbc",                         L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_MSSRbcVolume",                   L"JJ",  L"Predict_64_Get_MSSRbcVolume",                   L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_MaxPlasma",                      L"BJ",  L"Predict_64_Get_MaxPlasma",                      L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_hypovolemic",                    L"JJ",  L"Predict_64_Get_hypovolemic",                    L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_hypovolemiaDistance",            L"BJ",  L"Predict_64_Get_hypovolemiaDistance",            L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_HypoMargin",                     L"BJ",  L"Predict_64_Get_HypoMargin",                     L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_PlasmaTargetCannotChange",       L"JJ",  L"Predict_64_Get_PlasmaTargetCannotChange",       L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_MaxACRate",                      L"BJ",  L"Predict_64_Get_MaxACRate",                      L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_PredRBCDose",                    L"BJ",  L"Predict_64_Get_PredRBCDose",                    L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_PredRBCVolume",                  L"BJ",  L"Predict_64_Get_PredRBCVolume",                  L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_PredRBCCrit",                    L"BJ",  L"Predict_64_Get_PredRBCCrit",                    L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_RBCCalculatedCrit",              L"BJ",  L"Predict_64_Get_RBCCalculatedCrit",              L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_Status",                         L"JJ",  L"Predict_64_Get_Status",                         L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_Optimized",                      L"AJ",  L"Predict_64_Get_Optimized",                      L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_MaxQin",                         L"BJ",  L"Predict_64_Get_MaxQin",                         L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_PredVc",                         L"BJ",  L"Predict_64_Get_PredVc",                         L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_PredVp",                         L"BJ",  L"Predict_64_Get_PredVp",                         L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_PredVac",                        L"BJ",  L"Predict_64_Get_PredVac",                        L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_PredVrep",                       L"BJ",  L"Predict_64_Get_PredVrep",                       L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_PredTp",                         L"BJ",  L"Predict_64_Get_PredTp",                         L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_InfusionRate",                   L"BJ",  L"Predict_64_Get_InfusionRate",                   L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_Tc",                             L"BJ",  L"Predict_64_Get_Tc",                             L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_Ytarg",                          L"BJ",  L"Predict_64_Get_Ytarg",                          L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_Ec",                             L"BJ",  L"Predict_64_Get_Ec",                             L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_Qinc",                           L"BJ",  L"Predict_64_Get_Qinc",                           L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_Ydpur",                          L"BJ",  L"Predict_64_Get_Ydpur",                          L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_Vintarg",                        L"BJ",  L"Predict_64_Get_Vintarg",                        L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_Vptarg",                         L"BJ",  L"Predict_64_Get_Vptarg",                         L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_Vrtarg",                         L"BJ",  L"Predict_64_Get_Vrtarg",                         L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_Qcmr",                           L"BJ",  L"Predict_64_Get_Qcmr",                           L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_Vpmin",                          L"BJ",  L"Predict_64_Get_Vpmin",                          L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_Vinpur",                         L"BJ",  L"Predict_64_Get_Vinpur",                         L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Predict_64_Get_Ydch",                           L"BJ",  L"Predict_64_Get_Ydch",                           L"Product",         L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_lang",                        L"J",   L"Config_64_Get_key_lang",                        L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_lang",                        L"JJ",  L"Config_64_Set_key_lang",                        L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_height",                      L"J",   L"Config_64_Get_key_height",                      L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_height",                      L"JJ",  L"Config_64_Set_key_height",                      L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_weight",                      L"J",   L"Config_64_Get_key_weight",                      L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_weight",                      L"JJ",  L"Config_64_Set_key_weight",                      L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_date_format",                 L"J",   L"Config_64_Get_key_date_format",                 L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_date_format",                 L"JJ",  L"Config_64_Set_key_date_format",                 L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_time_format",                 L"J",   L"Config_64_Get_key_time_format",                 L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_time_format",                 L"JJ",  L"Config_64_Set_key_time_format",                 L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_decimal_delimiter",           L"J",   L"Config_64_Get_key_decimal_delimiter",           L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_decimal_delimiter",           L"JJ",  L"Config_64_Set_key_decimal_delimiter",           L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_crit_or_glob",                L"J",   L"Config_64_Get_key_crit_or_glob",                L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_crit_or_glob",                L"JJ",  L"Config_64_Set_key_crit_or_glob",                L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_set_time",                    L"J",   L"Config_64_Get_key_set_time",                    L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_set_time",                    L"JJ",  L"Config_64_Set_key_set_time",                    L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_set_date",                    L"J",   L"Config_64_Get_key_set_date",                    L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_set_date",                    L"JJ",  L"Config_64_Set_key_set_date",                    L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_set_audio",                   L"J",   L"Config_64_Get_key_set_audio",                   L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_set_audio",                   L"JJ",  L"Config_64_Set_key_set_audio",                   L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_pword",                       L"J",   L"Config_64_Get_key_pword",                       L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_pword",                       L"JJ",  L"Config_64_Set_key_pword",                       L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_proc_time",                   L"J",   L"Config_64_Get_key_proc_time",                   L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_proc_time",                   L"JJ",  L"Config_64_Set_key_proc_time",                   L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_return_press",                L"B",   L"Config_64_Get_key_return_press",                L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_return_press",                L"JB",  L"Config_64_Set_key_return_press",                L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_draw_press",                  L"B",   L"Config_64_Get_key_draw_press",                  L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_draw_press",                  L"JB",  L"Config_64_Set_key_draw_press",                  L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_custom_ratio",                L"B",   L"Config_64_Get_key_custom_ratio",                L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_custom_ratio",                L"JB",  L"Config_64_Set_key_custom_ratio",                L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_plasma_ratio",                L"B",   L"Config_64_Get_key_plasma_ratio",                L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_plasma_ratio",                L"JB",  L"Config_64_Set_key_plasma_ratio",                L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_ac_rate",                     L"J",   L"Config_64_Get_key_ac_rate",                     L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_ac_rate",                     L"JJ",  L"Config_64_Set_key_ac_rate",                     L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_post_crit",                   L"B",   L"Config_64_Get_key_post_crit",                   L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_post_crit",                   L"JB",  L"Config_64_Set_key_post_crit",                   L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_tbv_vol_setting",             L"J",   L"Config_64_Get_key_tbv_vol_setting",             L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_tbv_vol_setting",             L"JJ",  L"Config_64_Set_key_tbv_vol_setting",             L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_tbv_percent",                 L"B",   L"Config_64_Get_key_tbv_percent",                 L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_tbv_percent",                 L"JB",  L"Config_64_Set_key_tbv_percent",                 L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_weight_setting",              L"B",   L"Config_64_Get_key_weight_setting",              L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_weight_setting",              L"JB",  L"Config_64_Set_key_weight_setting",              L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_weight_less_than_vol",        L"B",   L"Config_64_Get_key_weight_less_than_vol",        L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_weight_less_than_vol",        L"JB",  L"Config_64_Set_key_weight_less_than_vol",        L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_weight_greater_than_vol",     L"B",   L"Config_64_Get_key_weight_greater_than_vol",     L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_weight_greater_than_vol",     L"JB",  L"Config_64_Set_key_weight_greater_than_vol",     L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_ml_per_kg",                   L"B",   L"Config_64_Get_key_ml_per_kg",                   L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_ml_per_kg",                   L"JB",  L"Config_64_Set_key_ml_per_kg",                   L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_drbc_body_vol",               L"B",   L"Config_64_Get_key_drbc_body_vol",               L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_drbc_body_vol",               L"JB",  L"Config_64_Set_key_drbc_body_vol",               L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_max_plasma_vol_during_plasma_collection", L"B",   L"Config_64_Get_key_max_plasma_vol_during_plasma_collection", L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_max_plasma_vol_during_plasma_collection", L"JB",  L"Config_64_Set_key_max_plasma_vol_during_plasma_collection", L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_max_plasma_vol_during_platelet_collection", L"B",   L"Config_64_Get_key_max_plasma_vol_during_platelet_collection", L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_max_plasma_vol_during_platelet_collection", L"JB",  L"Config_64_Set_key_max_plasma_vol_during_platelet_collection", L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_post_plat",                   L"B",   L"Config_64_Get_key_post_plat",                   L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_post_plat",                   L"JB",  L"Config_64_Set_key_post_plat",                   L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_max_draw_flow",               L"J",   L"Config_64_Get_key_max_draw_flow",               L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_max_draw_flow",               L"JJ",  L"Config_64_Set_key_max_draw_flow",               L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_min_replacement_volume",      L"J",   L"Config_64_Get_key_min_replacement_volume",      L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_min_replacement_volume",      L"JJ",  L"Config_64_Set_key_min_replacement_volume",      L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_plt_mss_split_notif",         L"J",   L"Config_64_Get_key_plt_mss_split_notif",         L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_plt_mss_split_notif",         L"JJ",  L"Config_64_Set_key_plt_mss_split_notif",         L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_override_pas_bag_vol",        L"J",   L"Config_64_Get_key_override_pas_bag_vol",        L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_override_pas_bag_vol",        L"JJ",  L"Config_64_Set_key_override_pas_bag_vol",        L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_drbc_alert",                  L"J",   L"Config_64_Get_key_drbc_alert",                  L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_drbc_alert",                  L"JJ",  L"Config_64_Set_key_drbc_alert",                  L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_drbc_threshold",              L"J",   L"Config_64_Get_key_drbc_threshold",              L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_drbc_threshold",              L"JJ",  L"Config_64_Set_key_drbc_threshold",              L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_plasma_rinseback",            L"J",   L"Config_64_Get_key_plasma_rinseback",            L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_plasma_rinseback",            L"JJ",  L"Config_64_Set_key_plasma_rinseback",            L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_saline_rinseback",            L"J",   L"Config_64_Get_key_saline_rinseback",            L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_saline_rinseback",            L"JJ",  L"Config_64_Set_key_saline_rinseback",            L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_audit_tracking",              L"J",   L"Config_64_Get_key_audit_tracking",              L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_audit_tracking",              L"JJ",  L"Config_64_Set_key_audit_tracking",              L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_air_removal",                 L"J",   L"Config_64_Get_key_air_removal",                 L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_air_removal",                 L"JJ",  L"Config_64_Set_key_air_removal",                 L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_blood_diversion",             L"J",   L"Config_64_Get_key_blood_diversion",             L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_blood_diversion",             L"JJ",  L"Config_64_Set_key_blood_diversion",             L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_mss_plt_on",                  L"J",   L"Config_64_Get_key_mss_plt_on",                  L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_mss_plt_on",                  L"JJ",  L"Config_64_Set_key_mss_plt_on",                  L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_mss_rbc_on",                  L"J",   L"Config_64_Get_key_mss_rbc_on",                  L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_mss_rbc_on",                  L"JJ",  L"Config_64_Set_key_mss_rbc_on",                  L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_show_pre_aas_flags",          L"J",   L"Config_64_Get_key_show_pre_aas_flags",          L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_show_pre_aas_flags",          L"JJ",  L"Config_64_Set_key_show_pre_aas_flags",          L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_plt_def_bag_vol",             L"J",   L"Config_64_Get_key_plt_def_bag_vol",             L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_plt_def_bag_vol",             L"JJ",  L"Config_64_Set_key_plt_def_bag_vol",             L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_rbc_def_bag_vol",             L"J",   L"Config_64_Get_key_rbc_def_bag_vol",             L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_rbc_def_bag_vol",             L"JJ",  L"Config_64_Set_key_rbc_def_bag_vol",             L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_rbc_ratio",                   L"J",   L"Config_64_Get_key_rbc_ratio",                   L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_rbc_ratio",                   L"JJ",  L"Config_64_Set_key_rbc_ratio",                   L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_rbc_replace_fluid",           L"J",   L"Config_64_Get_key_rbc_replace_fluid",           L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_rbc_replace_fluid",           L"JJ",  L"Config_64_Set_key_rbc_replace_fluid",           L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_rbc_fluid_percent",           L"B",   L"Config_64_Get_key_rbc_fluid_percent",           L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_rbc_fluid_percent",           L"JB",  L"Config_64_Set_key_rbc_fluid_percent",           L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_pls_amap_min",                L"J",   L"Config_64_Get_key_pls_amap_min",                L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_pls_amap_min",                L"JJ",  L"Config_64_Set_key_pls_amap_min",                L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_pls_amap_max",                L"J",   L"Config_64_Get_key_pls_amap_max",                L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_pls_amap_max",                L"JJ",  L"Config_64_Set_key_pls_amap_max",                L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_ysf",                         L"B",   L"Config_64_Get_key_ysf",                         L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_ysf",                         L"JB",  L"Config_64_Set_key_ysf",                         L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_guaranteed_yield",            L"J",   L"Config_64_Get_key_guaranteed_yield",            L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_guaranteed_yield",            L"JJ",  L"Config_64_Set_key_guaranteed_yield",            L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_confidence_level",            L"J",   L"Config_64_Get_key_confidence_level",            L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_confidence_level",            L"JJ",  L"Config_64_Set_key_confidence_level",            L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_coefficient_of_variation",    L"B",   L"Config_64_Get_key_coefficient_of_variation",    L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_coefficient_of_variation",    L"JB",  L"Config_64_Set_key_coefficient_of_variation",    L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_inlet_flow_ramp",             L"J",   L"Config_64_Get_key_inlet_flow_ramp",             L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_inlet_flow_ramp",             L"JJ",  L"Config_64_Set_key_inlet_flow_ramp",             L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_inlet_management",            L"J",   L"Config_64_Get_key_inlet_management",            L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_inlet_management",            L"JJ",  L"Config_64_Set_key_inlet_management",            L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_return_management",           L"J",   L"Config_64_Get_key_return_management",           L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_return_management",           L"JJ",  L"Config_64_Set_key_return_management",           L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_rsf",                         L"B",   L"Config_64_Get_key_rsf",                         L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_rsf",                         L"JB",  L"Config_64_Set_key_rsf",                         L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_male_only_plt",               L"J",   L"Config_64_Get_key_male_only_plt",               L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_male_only_plt",               L"JJ",  L"Config_64_Set_key_male_only_plt",               L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_male_only_plasma",            L"J",   L"Config_64_Get_key_male_only_plasma",            L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_male_only_plasma",            L"JJ",  L"Config_64_Set_key_male_only_plasma",            L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_complementary_plasma",        L"J",   L"Config_64_Get_key_complementary_plasma",        L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_complementary_plasma",        L"JJ",  L"Config_64_Set_key_complementary_plasma",        L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_ffp_volume",                  L"J",   L"Config_64_Get_key_ffp_volume",                  L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_ffp_volume",                  L"JJ",  L"Config_64_Set_key_ffp_volume",                  L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_rbc_crit",                    L"BJ",  L"Config_64_Get_key_rbc_crit",                    L"Index",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_rbc_crit",                    L"JJB", L"Config_64_Set_key_rbc_crit",                    L"Index,Value",     L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_rbc_dose",                    L"BJ",  L"Config_64_Get_key_rbc_dose",                    L"Index",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_rbc_dose",                    L"JJB", L"Config_64_Set_key_rbc_dose",                    L"Index,Value",     L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_rbc_mss",                     L"JJ",  L"Config_64_Get_key_rbc_mss",                     L"Index",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_rbc_mss",                     L"JJJ", L"Config_64_Set_key_rbc_mss",                     L"Index,Value",     L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_rbc_mss_volume",              L"JJ",  L"Config_64_Get_key_rbc_mss_volume",              L"Index",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_rbc_mss_volume",              L"JJJ", L"Config_64_Set_key_rbc_mss_volume",              L"Index,Value",     L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_plt_amap_min_yield",          L"BJ",  L"Config_64_Get_key_plt_amap_min_yield",          L"Index",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_plt_amap_min_yield",          L"JJB", L"Config_64_Set_key_plt_amap_min_yield",          L"Index,Value",     L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_plt_amap_max_yield",          L"BJ",  L"Config_64_Get_key_plt_amap_max_yield",          L"Index",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_plt_amap_max_yield",          L"JJB", L"Config_64_Set_key_plt_amap_max_yield",          L"Index,Value",     L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_plt_amap_conc",               L"BJ",  L"Config_64_Get_key_plt_amap_conc",               L"Index",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_plt_amap_conc",               L"JJB", L"Config_64_Set_key_plt_amap_conc",               L"Index,Value",     L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_plt_yield",                   L"BJ",  L"Config_64_Get_key_plt_yield",                   L"Index",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_plt_yield",                   L"JJB", L"Config_64_Set_key_plt_yield",                   L"Index,Value",     L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_plt_volume",                  L"BJ",  L"Config_64_Get_key_plt_volume",                  L"Index",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_plt_volume",                  L"JJB", L"Config_64_Set_key_plt_volume",                  L"Index,Value",     L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_plt_mss",                     L"JJ",  L"Config_64_Get_key_plt_mss",                     L"Index",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_plt_mss",                     L"JJJ", L"Config_64_Set_key_plt_mss",                     L"Index,Value",     L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_plt_pct_carryover",           L"JJ",  L"Config_64_Get_key_plt_pct_carryover",           L"Index",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_plt_pct_carryover",           L"JJJ", L"Config_64_Set_key_plt_pct_carryover",           L"Index,Value",     L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_pls_volume",                  L"BJ",  L"Config_64_Get_key_pls_volume",                  L"Index",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_pls_volume",                  L"JJB", L"Config_64_Set_key_pls_volume",                  L"Index,Value",     L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_platelet",                    L"JJ",  L"Config_64_Get_key_platelet",                    L"Index",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_platelet",                    L"JJJ", L"Config_64_Set_key_platelet",                    L"Index,Value",     L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_plasma",                      L"JJ",  L"Config_64_Get_key_plasma",                      L"Index",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_plasma",                      L"JJJ", L"Config_64_Set_key_plasma",                      L"Index,Value",     L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_rbc",                         L"JJ",  L"Config_64_Get_key_rbc",                         L"Index",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_rbc",                         L"JJJ", L"Config_64_Set_key_rbc",                         L"Index,Value",     L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_blood_type",                  L"JJ",  L"Config_64_Get_key_blood_type",                  L"Index",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_blood_type",                  L"JJJ", L"Config_64_Set_key_blood_type",                  L"Index,Value",     L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Get_key_time",                        L"BJ",  L"Config_64_Get_key_time",                        L"Index",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Config_64_Set_key_time",                        L"JJB", L"Config_64_Set_key_time",                        L"Index,Value",     L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Substate_64_Get_Qcc",                           L"BJJ", L"Substate_64_Get_Qcc",                           L"Product, Index",  L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Substate_64_Get_Qpc",                           L"BJJ", L"Substate_64_Get_Qpc",                           L"Product, Index",  L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Substate_64_Get_T",                             L"BJJ", L"Substate_64_Get_T",                             L"Product, Index",  L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Substate_64_Get_Qnret",                         L"BJJ", L"Substate_64_Get_Qnret",                         L"Product, Index",  L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Substate_64_Get_Vsvn",                          L"BJJ", L"Substate_64_Get_Vsvn",                          L"Product, Index",  L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Substate_64_Get_Tcn",                           L"BJJ", L"Substate_64_Get_Tcn",                           L"Product, Index",  L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Substate_64_Get_Td",                            L"BJJ", L"Substate_64_Get_Td",                            L"Product, Index",  L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Substate_64_Get_Tr",                            L"BJJ", L"Substate_64_Get_Tr",                            L"Product, Index",  L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Substate_64_Get_D",                             L"BJJ", L"Substate_64_Get_D",                             L"Product, Index",  L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Substate_64_Get_Qrinst",                        L"BJJ", L"Substate_64_Get_Qrinst",                        L"Product, Index",  L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Substate_64_Get_EndVin",                        L"BJJ", L"Substate_64_Get_EndVin",                        L"Product, Index",  L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Substate_64_Get_Vp",                            L"BJJ", L"Substate_64_Get_Vp",                            L"Product, Index",  L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Substate_64_Get_Vacp",                          L"BJJ", L"Substate_64_Get_Vacp",                          L"Product, Index",  L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Substate_64_Get_Vc",                            L"BJJ", L"Substate_64_Get_Vc",                            L"Product, Index",  L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Substate_64_Get_Vacc",                          L"BJJ", L"Substate_64_Get_Vacc",                          L"Product, Index",  L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Substate_64_Get_Vr",                            L"BJJ", L"Substate_64_Get_Vr",                            L"Product, Index",  L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Substate_64_Get_Vacr",                          L"BJJ", L"Substate_64_Get_Vacr",                          L"Product, Index",  L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Substate_64_Get_AccumVp",                       L"BJJ", L"Substate_64_Get_AccumVp",                       L"Product, Index",  L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Substate_64_Get_AccumVacp",                     L"BJJ", L"Substate_64_Get_AccumVacp",                     L"Product, Index",  L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Substate_64_Get_AccumVc",                       L"BJJ", L"Substate_64_Get_AccumVc",                       L"Product, Index",  L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Substate_64_Get_AccumVacc",                     L"BJJ", L"Substate_64_Get_AccumVacc",                     L"Product, Index",  L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Substate_64_Get_AccumTime",                     L"BJJ", L"Substate_64_Get_AccumTime",                     L"Product, Index",  L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Substate_64_Get_Vac",                           L"BJJ", L"Substate_64_Get_Vac",                           L"Product, Index",  L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Substate_64_Get_AccumVac",                      L"BJJ", L"Substate_64_Get_AccumVac",                      L"Product, Index",  L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Substate_64_Get_Vrep",                          L"BJJ", L"Substate_64_Get_Vrep",                          L"Product, Index",  L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Substate_64_Get_AccumVrep",                     L"BJJ", L"Substate_64_Get_AccumVrep",                     L"Product, Index",  L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Substate_64_Get_Qrep",                          L"BJJ", L"Substate_64_Get_Qrep",                          L"Product, Index",  L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Substate_64_Get_Hin",                           L"BJJ", L"Substate_64_Get_Hin",                           L"Product, Index",  L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Substate_64_Get_Facb",                          L"BJJ", L"Substate_64_Get_Facb",                          L"Product, Index",  L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Substate_64_Get_Facp",                          L"BJJ", L"Substate_64_Get_Facp",                          L"Product, Index",  L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Substate_64_Get_AvgHt",                         L"BJJ", L"Substate_64_Get_AvgHt",                         L"Product, Index",  L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Substate_64_Get_Hend",                          L"BJJ", L"Substate_64_Get_Hend",                          L"Product, Index",  L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Substate_64_Get_Qininstd",                      L"BJJ", L"Substate_64_Get_Qininstd",                      L"Product, Index",  L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Substate_64_Get_Qininstr",                      L"BJJ", L"Substate_64_Get_Qininstr",                      L"Product, Index",  L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Substate_64_Get_Qacinst",                       L"BJJ", L"Substate_64_Get_Qacinst",                       L"Product, Index",  L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Substate_64_Get_Qcinstd",                       L"BJJ", L"Substate_64_Get_Qcinstd",                       L"Product, Index",  L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Substate_64_Get_Qcinstr",                       L"BJJ", L"Substate_64_Get_Qcinstr",                       L"Product, Index",  L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Substate_64_Get_Qpinstd",                       L"BJJ", L"Substate_64_Get_Qpinstd",                       L"Product, Index",  L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Substate_64_Get_Qpinstr",                       L"BJJ", L"Substate_64_Get_Qpinstr",                       L"Product, Index",  L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Substate_64_Get_Qch",                           L"BJJ", L"Substate_64_Get_Qch",                           L"Product, Index",  L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Substate_64_Get_HypovolemiaDistance",           L"BJJ", L"Substate_64_Get_HypovolemiaDistance",           L"Product, Index",  L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Substate_64_Get_HypovolemiaMargin",             L"BJJ", L"Substate_64_Get_HypovolemiaMargin",             L"Product, Index",  L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Substate_64_Get_Yield",                         L"BJJ", L"Substate_64_Get_Yield",                         L"Product, Index",  L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Substate_64_Get_Csf",                           L"BJJ", L"Substate_64_Get_Csf",                           L"Product, Index",  L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Substate_64_Get_Rpm",                           L"BJJ", L"Substate_64_Get_Rpm",                           L"Product, Index",  L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Get_id",                           L"J",   L"Condition_64_Get_id",                           L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Set_id",                           L"JJ",  L"Condition_64_Set_id",                           L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Get_height",                       L"B",   L"Condition_64_Get_height",                       L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Set_height",                       L"JB",  L"Condition_64_Set_height",                       L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Get_weight",                       L"B",   L"Condition_64_Get_weight",                       L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Set_weight",                       L"JB",  L"Condition_64_Set_weight",                       L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Get_tbv",                          L"B",   L"Condition_64_Get_tbv",                          L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Set_tbv",                          L"JB",  L"Condition_64_Set_tbv",                          L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Get_precount",                     L"B",   L"Condition_64_Get_precount",                     L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Set_precount",                     L"JB",  L"Condition_64_Set_precount",                     L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Get_hct",                          L"B",   L"Condition_64_Get_hct",                          L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Set_hct",                          L"JB",  L"Condition_64_Set_hct",                          L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Get_bmi",                          L"B",   L"Condition_64_Get_bmi",                          L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Set_bmi",                          L"JB",  L"Condition_64_Set_bmi",                          L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Get_female",                       L"J",   L"Condition_64_Get_female",                       L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Set_female",                       L"JJ",  L"Condition_64_Set_female",                       L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Get_blood_type",                   L"J",   L"Condition_64_Get_blood_type",                   L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Set_blood_type",                   L"JJ",  L"Condition_64_Set_blood_type",                   L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Get_vin",                          L"B",   L"Condition_64_Get_vin",                          L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Set_vin",                          L"JB",  L"Condition_64_Set_vin",                          L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Get_vac",                          L"B",   L"Condition_64_Get_vac",                          L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Set_vac",                          L"JB",  L"Condition_64_Set_vac",                          L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Get_vplasma_bag",                  L"B",   L"Condition_64_Get_vplasma_bag",                  L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Set_vplasma_bag",                  L"JB",  L"Condition_64_Set_vplasma_bag",                  L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Get_vplasma_bag_ac",               L"B",   L"Condition_64_Get_vplasma_bag_ac",               L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Set_vplasma_bag_ac",               L"JB",  L"Condition_64_Set_vplasma_bag_ac",               L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Get_vcollect_bag",                 L"B",   L"Condition_64_Get_vcollect_bag",                 L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Set_vcollect_bag",                 L"JB",  L"Condition_64_Set_vcollect_bag",                 L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Get_vcollect_bag_ac",              L"B",   L"Condition_64_Get_vcollect_bag_ac",              L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Set_vcollect_bag_ac",              L"JB",  L"Condition_64_Set_vcollect_bag_ac",              L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Get_vrbc_bag",                     L"B",   L"Condition_64_Get_vrbc_bag",                     L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Set_vrbc_bag",                     L"JB",  L"Condition_64_Set_vrbc_bag",                     L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Get_vrbc_bag_ac",                  L"B",   L"Condition_64_Get_vrbc_bag_ac",                  L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Set_vrbc_bag_ac",                  L"JB",  L"Condition_64_Set_vrbc_bag_ac",                  L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Get_dose_rbc_bag",                 L"B",   L"Condition_64_Get_dose_rbc_bag",                 L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Set_dose_rbc_bag",                 L"JB",  L"Condition_64_Set_dose_rbc_bag",                 L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Get_vrep",                         L"B",   L"Condition_64_Get_vrep",                         L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Set_vrep",                         L"JB",  L"Condition_64_Set_vrep",                         L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Get_vsaline_bolus",                L"B",   L"Condition_64_Get_vsaline_bolus",                L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Set_vsaline_bolus",                L"JB",  L"Condition_64_Set_vsaline_bolus",                L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Get_platelet_yield",               L"B",   L"Condition_64_Get_platelet_yield",               L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Set_platelet_yield",               L"JB",  L"Condition_64_Set_platelet_yield",               L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Get_time_of_vincv",                L"B",   L"Condition_64_Get_time_of_vincv",                L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Set_time_of_vincv",                L"JB",  L"Condition_64_Set_time_of_vincv",                L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Get_vincv",                        L"B",   L"Condition_64_Get_vincv",                        L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Set_vincv",                        L"JB",  L"Condition_64_Set_vincv",                        L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Get_vin_epca_start",               L"B",   L"Condition_64_Get_vin_epca_start",               L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Set_vin_epca_start",               L"JB",  L"Condition_64_Set_vin_epca_start",               L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Get_rbc_s1",                       L"B",   L"Condition_64_Get_rbc_s1",                       L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Set_rbc_s1",                       L"JB",  L"Condition_64_Set_rbc_s1",                       L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Get_rbc_s2",                       L"B",   L"Condition_64_Get_rbc_s2",                       L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Set_rbc_s2",                       L"JB",  L"Condition_64_Set_rbc_s2",                       L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Get_rbc_prime",                    L"B",   L"Condition_64_Get_rbc_prime",                    L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Set_rbc_prime",                    L"JB",  L"Condition_64_Set_rbc_prime",                    L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Get_rbc_s1_double",                L"B",   L"Condition_64_Get_rbc_s1_double",                L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Set_rbc_s1_double",                L"JB",  L"Condition_64_Set_rbc_s1_double",                L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Get_rbc_s2_double",                L"B",   L"Condition_64_Get_rbc_s2_double",                L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Set_rbc_s2_double",                L"JB",  L"Condition_64_Set_rbc_s2_double",                L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Get_rbc_double",                   L"B",   L"Condition_64_Get_rbc_double",                   L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Set_rbc_double",                   L"JB",  L"Condition_64_Set_rbc_double",                   L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Get_substate",                     L"J",   L"Condition_64_Get_substate",                     L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Set_substate",                     L"JJ",  L"Condition_64_Set_substate",                     L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Get_qch_min",                      L"B",   L"Condition_64_Get_qch_min",                      L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Set_qch_min",                      L"JB",  L"Condition_64_Set_qch_min",                      L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Get_qch_cur",                      L"B",   L"Condition_64_Get_qch_cur",                      L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Set_qch_cur",                      L"JB",  L"Condition_64_Set_qch_cur",                      L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Get_npurges",                      L"J",   L"Condition_64_Get_npurges",                      L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Set_npurges",                      L"JJ",  L"Condition_64_Set_npurges",                      L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Get_adjusted_hct",                 L"B",   L"Condition_64_Get_adjusted_hct",                 L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Set_adjusted_hct",                 L"JB",  L"Condition_64_Set_adjusted_hct",                 L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Get_current_recovery",             L"J",   L"Condition_64_Get_current_recovery",             L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Set_current_recovery",             L"JJ",  L"Condition_64_Set_current_recovery",             L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Get_vin_clearline",                L"B",   L"Condition_64_Get_vin_clearline",                L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Set_vin_clearline",                L"JB",  L"Condition_64_Set_vin_clearline",                L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Get_wbc_purge_start_time",         L"B",   L"Condition_64_Get_wbc_purge_start_time",         L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Set_wbc_purge_start_time",         L"JB",  L"Condition_64_Set_wbc_purge_start_time",         L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Get_wbc_purge_type",               L"J",   L"Condition_64_Get_wbc_purge_type",               L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Set_wbc_purge_type",               L"JJ",  L"Condition_64_Set_wbc_purge_type",               L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Get_substate_start_time",          L"B",   L"Condition_64_Get_substate_start_time",          L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Set_substate_start_time",          L"JB",  L"Condition_64_Set_substate_start_time",          L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Get_midrun_entered",               L"J",   L"Condition_64_Get_midrun_entered",               L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Set_midrun_entered",               L"JJ",  L"Condition_64_Set_midrun_entered",               L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Get_proctime",                     L"B",   L"Condition_64_Get_proctime",                     L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Set_proctime",                     L"JB",  L"Condition_64_Set_proctime",                     L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Get_type",                         L"J",   L"Condition_64_Get_type",                         L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Set_type",                         L"JJ",  L"Condition_64_Set_type",                         L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Get_rbc_detector_calibrated",      L"A",   L"Condition_64_Get_rbc_detector_calibrated",      L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Set_rbc_detector_calibrated",      L"JA",  L"Condition_64_Set_rbc_detector_calibrated",      L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Get_qin",                          L"B",   L"Condition_64_Get_qin",                          L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Set_qin",                          L"JB",  L"Condition_64_Set_qin",                          L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Get_qrp",                          L"B",   L"Condition_64_Get_qrp",                          L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Set_qrp",                          L"JB",  L"Condition_64_Set_qrp",                          L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Get_ir",                           L"B",   L"Condition_64_Get_ir",                           L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Set_ir",                           L"JB",  L"Condition_64_Set_ir",                           L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Get_ratio",                        L"B",   L"Condition_64_Get_ratio",                        L"",                L"2", L"Predict 6.4", L"", L"", L"", L"", },
{ L"Condition_64_Set_ratio",                        L"JB",  L"Condition_64_Set_ratio",                        L"Value",           L"2", L"Predict 6.4", L"", L"", L"", L"", },
};

static const int kFunctionCount = sizeof(kFunctionList) / (sizeof(LPWSTR) * 10);

#endif
