/*******************************************************************************
 *
 * Copyright (c) 2000 by Gambro BCT, Inc.  All rights reserved.
 *
 * TITLE:      alarms.h
 *
 * ABSTRACT:   This file contains definitions that exist throughout the procedure
 *                domain for alarm handling.
 *
 ******************************************************************************/

/**********************************************************************************
* NOTE: This file is now shared with Vista. Take care when adding new dependencies
**********************************************************************************/

#ifndef ALARMS_H  //  Prevents multiple compilations.
#define ALARMS_H

#ifndef WIN32
#include "trima_datalog.h"
#endif

enum ALARM_VALUES
{
   FIRST_PROCEDURE_ALARM,             // Don't add procedure alarms before this enum
   ACCESS_NEGATIVE_ALARM_NOT_REACHED,
   ACCESS_PRESSURE_DECAY_FAILURE,
   AC_CLOSURE_FAILED_ALERT,
   AC_CLOSURE_FAILED_ALARM,
   AC_DETECTED_PRIOR_TO_AC_PRIME_FAILURE,
   AC_DETECTION_ALARM,
   AC_LEVEL_ALARM,
   AC_NOT_REMOVED_ALERT,
   AC_OCCLUSION_DETECTED,
   AC_PRIME_INLET_ALARM,
   APS_AUTO_ZERO_FAILED_RANGE,
   APS_AUTO_ZERO_FAILED_MAX,
   APS_AUTO_ZERO_FAILED_MIN,
   APS_DECOUPLING,
   APS_DECOUPLING_PAUSE,

   APS_DURING_PAUSE_HI, // IT 13427  changed name to high pressure alarm

   APS_PAUSE,
   APS_PUMPS_SLOW,
   APS_TOO_HIGH_ALERT,
   UNUSED_20,
   APS_TOO_HIGH_ALERT_MSS,
   APS_TOO_HIGH_ALARM_MSS,
   APS_HIGH_MSS_P1_OK_ALERT,
   APS_TOO_HIGH_PTF_ALERT,
   APS_TOO_LOW,
   BARCODE_INFO_ALARM,
   CASSETTE_FAILURE,
   CASSETTE_INVALID_ALARM,
   CASSETTE_REF_MISMATCH_ALARM,
   CASSETTE_UNRECOGNIZED_ALARM,
   CENTRIFUGE_HARDWARE_FAILURE,
   CENTRIFUGE_INTEGRAL_FAILURE,
   CENTRIFUGE_SHUTDOWN_FAILURE,
   CFR11_TRACKING_ALARM,
   CHANNEL_CLAMP_NOT_CLOSED_ALERT,
   CHANNEL_CLAMP_NOT_CLOSED_ADDITION_ALERT,
   CHANNEL_VOLUME_REMAINING_HIGH,
   COLLECT_VALVE_FAILURE,
   CONCENTRATION_OUT_OF_TOLERANCE,
   CPS_HIGH_DURING_RBC_COLLECT_ALARM,
   CPS_HIGH_DURING_RBC_COLLECT_ALERT,
   CPS_HIGH_DURING_RBC_COLLECT_PROD2_OK_ALERT,
   CPS_PTF_BASELINE_TEST_ALERT,
   CPS_PTF_BASELINE_TEST_ALARM,
   CPS_PTF_PRIME_TEST,
   CPS_TOO_HIGH_ALARM,
   CPS_TOO_HIGH_ALERT_NO_CLAMP,
   CPS_TOO_HIGH_ALERT_ONE_CLAMP,
   CPS_TOO_HIGH_ALERT_THREE_CLAMP,
   CPS_OUT_OF_RANGE_AT_SET_LOWER,
   UNUSED_51,
   DISCONNECT_TEST_ALARM,
   DISCONNECT_TEST_ALERT,
   DISCONNECT_TEST_MSS_ALERT,
   DISCONNECT_TEST_MSS_ALARM,
   DOOR_LATCH_FAILURE,
   DOOR_LOCK_ALARM,
   DOOR_OPEN_ALARM,
   DRBC_SPLIT_ALERT,
   EVACUATION_PRESSURE_ALERT,
   EVACUATION_PRESSURE_ALERT_FINAL,
   FAILURE_TO_CLOSE_CROSSOVER,
   FAILURE_TO_PRESSURIZE_INLET,
   FAILURE_TO_PRESSURIZE_INLET_NON_RAS_SET, // Same as above, but we also may have loaded a RAS set for a non-RAS REF.
   FAILURE_TO_PRESSURIZE_INLET_RAS_SET,     // Same as above, but we also may have loaded a non-RAS set for a RAS REF, or forgotten to clamp the crossover.
   FAILURE_TO_RELIEVE_PRESSURE,
   FIRST_CYCLE_TOO_LATE_ALARM,
   FIRST_CYCLE_TOO_SOON_ALARM,
   HIGH_CENTRIFUGE_COMMAND,
   HYPOVOLEMIA_ALARM,
   INLET_VOLM_ALARM,
   LEAK_DETECTED_ALERT,
   LEAK_DETECTOR_ERROR_FAILURE,
   LEAK_TEST_FAILURE,
   LOW_LEVEL_DETECTED_PRIOR_TO_EXPECTED,
   LOW_LEVEL_SENSOR_SEEN_TOO_LATE_FAILURE,
   LOW_LEVEL_SENSOR_SEEN_TOO_SOON_FAILURE,
   LOW_PLATELET_CONCENTRATION_ALERT,
   MAINTAIN_DONOR_ACCESS_ALERT,
   MSS_PRIME_DELAY_RBC_ALERT,    // RBC  R1
   MSS_PRIME_TOO_SOON_RBC_ALARM, // RBC  A1
   MSS_PRIME_TOO_SOON_PLT_ALERT, // PLT  R1
   MSS_PRIME_DELAY_PLT_ALERT,    // PLT  R1
   MSS_PLT_SS_EMPTY,             // PLT OP
   DEAD_ALARM_6,
   MSS_RBC_SS_EMPTY,
   MSS_DRBC_SS_EMPTY,
   minus12V_TOO_HIGH,
   minus12V_TOO_LOW,
   MOTOR_FAILED_TO_MAINTAIN_SPEED,
   ONE_MINUTE_PAUSE,
   OVERTEMP_ALARM,
   OVERTEMP_FAILURE,
   PAUSE_BEFORE_SPILLOVER,
   PAUSE_BUTTON_ALARM,
   PERSISTENT_SPILLOVER_ALARM,
   plus64V_TOO_HIGH,
   plus64V_TOO_LOW,
   plus24V_TOO_HIGH,
   plus24V_TOO_LOW,
   plus12V_TOO_HIGH,
   plus12V_TOO_LOW,
   PLASMA_VALVE_FAILURE,
   POWER_FAIL_CONTINUE,
   POWER_FAIL_RINSEBACK,
   POWER_FAIL_ABORT,
   POWER_TEST_FAILURE,
   PREDICTION_PAUSE,
   PRIME_FAILURE,
   PROCEDURE_MODIFIED,
   PUMP_RPM_COMMAND_FAILURE,
   RBC_DETECTOR_CAL_FAILURE,
   RBC_VALVE_FAILURE,
   REPLACEMENT_FLUID_ALARM,
   REPLACEMENT_FLUID_BOLUS_ALARM,
   REPLACEMENT_FLUID_NEW_BAG_ALARM,
   REPLACEMENT_FLUID_ALARM_RINSEBACK,
   RESERVOIR_ALARM,
   RESERVOIR_CHECK_SILENT_ALARM,      // this alarm is used to double checks the ULS to mitigate false FCV too low conditions (IT9254)


   RESERVOIR_DRAW_TOO_LONG_ALARM_NO_CLAMP,
   RESERVOIR_DRAW_TOO_SHORT_ALARM_NO_CLAMP,
   RESERVOIR_RETURN_TOO_LONG_ALARM_NO_CLAMP,
   RESERVOIR_RETURN_TOO_SHORT_ALARM_NO_CLAMP,

   RESERVOIR_DRAW_TOO_LONG_ALARM_ONE_CLAMP,
   RESERVOIR_DRAW_TOO_SHORT_ALARM_ONE_CLAMP,
   RESERVOIR_RETURN_TOO_LONG_ALARM_ONE_CLAMP,
   RESERVOIR_RETURN_TOO_SHORT_ALARM_ONE_CLAMP,

   RESERVOIR_DRAW_TOO_LONG_ALARM_THREE_CLAMP,
   RESERVOIR_DRAW_TOO_SHORT_ALARM_THREE_CLAMP,
   RESERVOIR_RETURN_TOO_LONG_ALARM_THREE_CLAMP,
   RESERVOIR_RETURN_TOO_SHORT_ALARM_THREE_CLAMP,

   RESERVOIR_DRAW_TOO_LONG_ALARM_RBC_PL_NO_CLAMP,
   RESERVOIR_DRAW_TOO_LONG_ALARM_RBC_PL_ONE_CLAMP,

   RESERVOIR_RETURN_TOO_LONG_ALARM_A1,
   RETURN_LINE_OCCLUSION,
   RETURN_LINE_OCCLUSION_A1,
   SAL_RINSEBACK_RETURN_TOO_HIGH,
   SET_IDENTIFICATION_ALARM,
   SPILLOVER_DETECTED,
   STOP_BUTTON_ALARM,
   TEN_MINUTE_PAUSE,
   TEN_MINUTE_PAUSE_ALARM,
   TOO_MANY_RESERVOIR_DRAW_ALARMS,
   TOO_MANY_RESERVOIR_RETURN_ALARMS,
   RESERVOIR_FULL_AFTER_RETURN,
   UNLOADING_BAD_CASSETTE_POSITION,
   VALVE_HARDWARE_FAILURE,
   VALVE_TEST_FAILURE,
   HEMOLYSIS_DETECTED_ALARM,
   GENERIC_PLT_WBC_CONTAMINATION_ALERT,
   AC_CLOSURE_FAILED_CONTINUE_PAS_ALARM,
   GENERIC_PLT_WBC_CONTAMINATION_OBTRUSIVE_ALERT,

   CONTROL_PRE_WATCHDOG_PAUSE,
   EVACUATION_PRESSURE_ALERT_JP,

   APS_AUTO_ZERO_FILE_ERROR,

   MOTOR_INTEGRATION_ERROR,
   MOTOR_VOLUME_ERROR,
   MOTOR_DISABLED,

   DEAD_ALARM_1,
   DEAD_ALARM_2,
   DEAD_ALARM_3,

   FAILURE_TO_PRESSURIZE_INLET_FINAL,
   AUTOFLOW_TIME_ALERT,

   APS_DURING_PAUSE_LOW,              // IT 13427
   APS_TOO_HIGH_ALARM_MSS_WITH_PAS,
   SILENT_PAUSE_FOR_RET_TOO_SHORT_CHECK,
   SILENT_PAUSE_FOR_MICROAIR_CHECK,

   MSS_MISCONNECTED_2ND_PAS_BAG,      // IT 13701
   AUTOFLOW_TIME_ALARM,
   AUTOFLOW_TIME_DQ,                  // This alarm used when procedure time exceeds configured maximum procedure time due to auto flow adjustment
   NON_AUTOFLOW_TIME_DQ,              // This alarm used when procedure time exceeds configured maximum procedure time due to non auto flow adjustment event
   APS_PAUSE_DURING_RETURN,           // Is set when there is APS low during return cycle

   LAST_PROCEDURE_ALARM,              // Don't add procedure alarms after this enum

   //
   //
   //  These alarms are translated from "fatal errors" (ref IT 4602)
   //
   //
   FIRST_FATAL_ERROR_ALARM=1000,             // Don't add fatal alarms before this enum
   BARCODE_INITIALIZATION_ALARM,
   BITMAP_LOAD_FAILURE,
   CAL_DAT_BAD_FILE,
   CAL_DAT_NO_APS_CAL,
   CAL_DAT_NO_CPS_CAL,
   CAL_DAT_NO_RBC_CAL,
   CAL_DAT_PARSE_ERROR,
   CAL_DAT_VALUE_NOT_FOUND,
   CAL_DAT_VALUE_OUT_OF_RANGE,
   CFR11_LOG_FILE_ERROR,
   CASSETTE_DAT_FILE_BAD_CRC,
   CASSETTE_DAT_FILE_INVALID_ENTRY,
   CASSETTE_DAT_FILE_OPEN_ERROR,
   CASSETTE_DAT_FILE_PARSE_ERROR,
   COBE_CONFIG_BAD_FILE,
   COBE_CONFIG_VALUE_NOT_FOUND,
   COBE_CONFIG_VALUE_OUT_OF_RANGE,
   COBE_CONFIG_PARSE_ERROR,
   CONFIGDAT_BAD_FILE,
   CONFIGDAT_VALUE_NOT_FOUND,
   CONFIGDAT_VALUE_OUT_OF_RANGE,
   CONFIGDAT_PARSE_ERROR,
   CONFIGDAT_WRITE_ERROR,
   CPUID_BAD_CONTROL_DATA_FILE,
   CPUID_BAD_SAFETY_DATA_FILE,
   CPUID_NO_CONTROL_DATA_FILE,
   CPUID_NO_SAFETY_DATA_FILE,
   CPUID_CONTROL_HW_INVALID,
   CPUID_SAFETY_HW_INVALID,
   FLOW_CALCULATION_ERROR,
   GUI_UNEXPECTED_CHOICE,
   GUI_VERIFPRD_NO_EXTENDED_TEXT,
   HARDWARE_FAULT,
   HW_DAT_BAD_FILE,
   HW_DAT_VALUE_NOT_FOUND,
   HW_DAT_VALUE_OUT_OF_RANGE,
   HW_DAT_PARSE_ERROR,
   HYPOVOLEMIA_NOT_INITIALIZED,
   INTERNAL_ATOD_ERROR,
   INTERNAL_TIMING_ERROR,
   INVALID_ALARM_FAULT,
   MEMORY_TEST_OSINFO_FAILURE,
   MEMORY_TEST_SAFETY_MEMORY_INSUFFICIENT,
   UNUSED_1044,
   PREDICT_BAD_TARGET_SUBSTATE,
   PREDICT_INVALID_GUI_REQUEST,
   PREDICT_INVALID_MODIFY_REQUEST,
   PREDICT_NO_SELECTED_PROCEDURE,
   PREDICT_NOT_RESPONDING,
   PROC_STATES_FILE_NOT_FOUND,
   PROC_STATES_FILE_READ_ERROR,
   PROC_STATES_INIT_ERROR,
   PROC_STATES_PROCESSING_ERROR,
   RANDOM_FILE_STORAGE_ERROR,
   RBC_DAT_BAD_FILE,
   RBC_DAT_VALUE_NOT_FOUND,
   RBC_DAT_VALUE_OUT_OF_RANGE,
   RBC_DAT_PARSE_ERROR,
   RET_OCC_MONITOR_FAILURE,
   SAFETY_NOT_RESPONDING,
   SAFETY_STATUS_INACTIVE,
   SETCONFIG_DAT_FILE_BAD_CRC,
   SETCONFIG_DAT_FILE_INVALID_ENTRY,
   SETCONFIG_DAT_FILE_OPEN_ERROR,
   SETCONFIG_DAT_FILE_PARSE_ERROR,
   SOFTWARE_CRC_CHECK_FAILURE,
   VIP_CANT_BIND_SOCKET,
   VIP_CANT_LISTEN_ON_SOCKET,
   VTARGETCHECKER_DEFAULT,
   SOUNDS_DAT_BAD_FILE,
   SOUNDS_DAT_VALUE_NOT_FOUND,
   SOUNDS_DAT_VALUE_OUT_OF_RANGE,
   SOUNDS_DAT_PARSE_ERROR,
   SOUNDS_DAT_CRC_CHECK_FAILURE,
   SW_CONFIG_VALUE_NOT_FOUND,
   STRING_INFO_FILE_ERROR,
   UNUSED_1077,
   CPS_TOO_HIGH_ALERT_THREE_CLAMP_PTF,
   CONTROL_SOFT_WATCHDOG,
   DEAD_ALARM_5,
   GUI_TRANSACTION_ERROR,
   LAST_FATAL_ERROR_ALARM,              // Don't add fatal alarms after this enum

   ////////////////////////////////////////////////////////////////////////////////

   FIRST_SAFETY_ALARM=32768,              // MUST BE FIRST SAFETY ALARM!!!

   PWR_SWITCH_24V_FAILED,                 // 24 V T1
   PWR_SWITCH_64V_FAILED,                 // 64V T1
   PWR_SWITCH_BOTH_FAILED,                // both pwr T1
   DONOR_SEX_INVALID,                     // TBV Validation
   TBV_UNITS_UNKNOWN,                     //
   DONOR_WEIGHT_TOO_LOW,                  //
   DONOR_WEIGHT_TOO_HIGH,                 //
   DONOR_HEIGHT_TOO_LOW,                  //
   DONOR_HEIGHT_TOO_HIGH,                 //
   DONOR_TBV_TOO_HIGH,                    //
   DONOR_TBV_TOO_LOW,                     //
   TBV_COMPARISON_FAILED,                 //
   CENTRIFUGE_OVERSPEED,                  // T0 Monitoring
   CENTRIFUGE_ERROR,                      // T0 Monitoring
   VALVE_LED_ERROR,                       // T0 Monitoring
   RESERVOIR_FAILED_T0,                   // Reservoir low level sensor T0 during SELF_TEST,STARTUP_PRELOAD
   STATE_TRANSITION_INVALID,              //
   SW_FAULT,                              //
   DONOR_AIR_ALARM,                       //
   INLET_PUMP_HALL_TOO_BIG,               // safety pump speed monitoring
   INLET_PUMP_HALL_TOO_SMALL,             //
   RETURN_PUMP_HALL_TOO_BIG,              //
   RETURN_PUMP_HALL_TOO_SMALL,            //
   AC_PUMP_HALL_TOO_BIG,                  //
   AC_PUMP_HALL_TOO_SMALL,                //
   PLASMA_PUMP_HALL_TOO_BIG,              //
   PLASMA_PUMP_HALL_TOO_SMALL,            //
   PLATELET_PUMP_HALL_TOO_BIG,            //
   PLATELET_PUMP_HALL_TOO_SMALL,          //
   DONOR_HYPOVOLEMIA_ALARM,               //
   AC_INFUSION_HIGH_ALARM,                //
   DRAW_CYCLE_TOO_BIG,                    // Reservoir monitoring
   DEAD_ALARM_4,                          //
   DOOR_NOT_LOCKED_CENTIFUGE_SPINNING,    //
   INAPPROPRIATE_CASSETTE_MOVEMENT,       //
   PRIME_TOO_SOON,                        // fluid detected at low level sensor too soon during prior to completion of BLOOD_PRIME
   PAUSE_SW_FAILED,                       // control did not command zero speeds w/in 2 secs from key press
   STOP_SW_FAILED,                        // control did not command zero speeds w/in 2 secs from key press.
   AC_RATIO_TOO_LOW_ALARM,                //
   AC_RATIO_TOO_HIGH_ALARM,               //
   AC_OFF_DURING_DRAW,                    // ac pump commanded off with inlet flow exceeding return flow.
   SAFETY_STATUS_COMM_ALARM,              // have not gotten safety status within allowable time
   AC_ON_DURING_RETURN,
   RBC_OUT_OF_POSITION,
   PLASMA_OUT_OF_POSITION,
   PLATELET_OUT_OF_POSITION,
   DONOR_HCT_RANGE_ERROR,
   DONOR_PRECOUNT_RANGE_ERROR,
   RBC_WB_PROCESSED_TOO_LARGE,
   SAFETY_T1_FAILURE,
   FIRST_DRAW_CYCLE_TOO_SMALL,            // first draw cycle must be a minimum volume for infusion control
   CASSETTE_NOT_DOWN,
   INAPPROPRIATE_AC_PUMP_MOVEMENT,
   UNUSED_1,
   RETURN_PUMP_SPEED_ALARM_RB,            // return pump speed > 100 ml/min during rb
   HYPERVOLEMIA_DETECTED,
   LAST_SAFETY_ALARM,                     // Don't add safety alarms after this enum

   NULL_ALARM
};

// Other alarm enums and structs have been moved to
// alarmEnums.h to make this file easier to parse with sed.
#include "alarmEnums.h"

#endif /* ifndef ALARMS_H */

/* FORMAT HASH dcc497b6842b054fc062930a89c96fd2 */
