#ifndef ____VerifyFlags__
#define ____VerifyFlags__

// This is the list of verify flags.
// NOTE: Insert new enumeration symbols above NO_FLAG.
// And don't forget to update ENUMERATED_FLAG_NAME() below!
enum ENUMERATED_FLAG
{
   VERIFY_PLATELET_WBCS,
   VERIFY_PLATELET_YIELD,
   VERIFY_PLASMA_VOL,
   VERIFY_PLASMA_WBCS,
   VERIFY_RBC_VOL,
   VERIFY_RBC_WBCS,
   VERIFY_RBC_QUALITY,
   VERIFY_RBC_VOL_PROD2,  // Flags for 2nd dRBC product
   VERIFY_RBC_WBCS_PROD2, // Flags for 2nd dRBC product
   VERIFY_RBC_QUALITY_PROD2,
   CONC_OUT_OF_RANGE,
   NO_FLAG,               // Effectively (or AKA) the end of the list
};

// Helper macro for deriving string from enum
#define ENUM_AS_STRING_IF_EQ(f, e)  (f == e) ? #e :

#if defined(PQMONITOR_BASE)
#define ENUMERATED_FLAG_NAME(f) \
   (\
      ENUM_AS_STRING_IF_EQ(f, VERIFY_PLATELET_WBCS) \
      ENUM_AS_STRING_IF_EQ(f, VERIFY_PLATELET_YIELD) \
      ENUM_AS_STRING_IF_EQ(f, VERIFY_PLASMA_VOL) \
      ENUM_AS_STRING_IF_EQ(f, VERIFY_PLASMA_WBCS) \
      ENUM_AS_STRING_IF_EQ(f, VERIFY_RBC_VOL) \
      ENUM_AS_STRING_IF_EQ(f, VERIFY_RBC_WBCS) \
      ENUM_AS_STRING_IF_EQ(f, VERIFY_RBC_QUALITY) \
      ENUM_AS_STRING_IF_EQ(f, VERIFY_RBC_VOL_PROD2) \
      ENUM_AS_STRING_IF_EQ(f, VERIFY_RBC_WBCS_PROD2) \
      ENUM_AS_STRING_IF_EQ(f, VERIFY_RBC_QUALITY_PROD2) \
      ENUM_AS_STRING_IF_EQ(f, CONC_OUT_OF_RANGE) \
      ENUM_AS_STRING_IF_EQ(f, NO_FLAG) \
      "UNKNOWN_FLAG" \
   )
#endif // PQMONITOR_BASE


// This is the list of possible reasons for any given verify flag to be set.
// NOTE: Insert new enumeration symbols between NULL_REASON and LAST_REASON.
// The code counts on NULL_REASON being first and LAST_REASON being last.
// And don't forget to update ENUMERATED_REASON_NAME() below!
enum ENUMERATED_REASON
{
   NULL_REASON,
   SPILL_DETECTION,
   SPILL_RECOVERY,
   STOPPED_CENTRIFUGE,
   RBC_DETECTOR_ERROR,
   HIGH_PLATELET_CONCENTRATION,
   LOW_CHAMBER_FLOW,
   HIGH_DELTA_HCT,
   AIR_BLOCK_RECOVERY,
   HIGH_HCT,
   OBSOLETE_REASON_1, // obsolete; keep to preserve numbering from 5.1/5.2.
   PLATELET_CONTAMINANT_DETECTION,
   RUN_ENDED_EARLY,
   LOW_DETECTED_PLATELET_CONCENTRATION,
   HIGH_PLATELET_YIELD_DEVIATION,
   LONG_DRAW,
   SHORT_DRAW,
   PLATELET_VOLUME_ERROR,
   PLASMA_VOLUME_ERROR,
   RBC_VOLUME_ERROR,
   PLATELET_CONCENTRATION_BELOW_STORAGE_RANGE,
   PLATELET_CONCENTRATION_ABOVE_STORAGE_RANGE,
   METERED_SOLUTION_VOLUME_ERROR,
   RINSEBACK_NOT_COMPLETED,
   CPS_HIGH,
   APS_HIGH,
   FINAL_CONC_NOT_ACHIEVED,
   METERED_SOLUTION_PRIME_ERROR,
   CHANNEL_CLAMP_ERROR,
   METERED_SOLUTION_ENDED_BY_OPERATOR,
   TRIPLE_PPC_AS_NON_LEUKOREDUCED,
   LAST_REASON
};

#if defined(PQMONITOR_BASE)
#define ENUMERATED_REASON_NAME(r) \
   (\
      ENUM_AS_STRING_IF_EQ(r, NULL_REASON) \
      ENUM_AS_STRING_IF_EQ(r, SPILL_DETECTION) \
      ENUM_AS_STRING_IF_EQ(r, SPILL_RECOVERY) \
      ENUM_AS_STRING_IF_EQ(r, STOPPED_CENTRIFUGE) \
      ENUM_AS_STRING_IF_EQ(r, RBC_DETECTOR_ERROR) \
      ENUM_AS_STRING_IF_EQ(r, HIGH_PLATELET_CONCENTRATION) \
      ENUM_AS_STRING_IF_EQ(r, LOW_CHAMBER_FLOW) \
      ENUM_AS_STRING_IF_EQ(r, HIGH_DELTA_HCT) \
      ENUM_AS_STRING_IF_EQ(r, AIR_BLOCK_RECOVERY) \
      ENUM_AS_STRING_IF_EQ(r, HIGH_HCT) \
      ENUM_AS_STRING_IF_EQ(r, PLATELET_CONTAMINANT_DETECTION) \
      ENUM_AS_STRING_IF_EQ(r, RUN_ENDED_EARLY) \
      ENUM_AS_STRING_IF_EQ(r, LOW_DETECTED_PLATELET_CONCENTRATION) \
      ENUM_AS_STRING_IF_EQ(r, HIGH_PLATELET_YIELD_DEVIATION) \
      ENUM_AS_STRING_IF_EQ(r, LONG_DRAW) \
      ENUM_AS_STRING_IF_EQ(r, SHORT_DRAW) \
      ENUM_AS_STRING_IF_EQ(r, PLATELET_VOLUME_ERROR) \
      ENUM_AS_STRING_IF_EQ(r, PLASMA_VOLUME_ERROR) \
      ENUM_AS_STRING_IF_EQ(r, RBC_VOLUME_ERROR) \
      ENUM_AS_STRING_IF_EQ(r, PLATELET_CONCENTRATION_BELOW_STORAGE_RANGE) \
      ENUM_AS_STRING_IF_EQ(r, PLATELET_CONCENTRATION_ABOVE_STORAGE_RANGE) \
      ENUM_AS_STRING_IF_EQ(r, METERED_SOLUTION_VOLUME_ERROR) \
      ENUM_AS_STRING_IF_EQ(r, RINSEBACK_NOT_COMPLETED) \
      ENUM_AS_STRING_IF_EQ(r, CPS_HIGH) \
      ENUM_AS_STRING_IF_EQ(r, APS_HIGH) \
      ENUM_AS_STRING_IF_EQ(r, FINAL_CONC_NOT_ACHIEVED) \
      ENUM_AS_STRING_IF_EQ(r, METERED_SOLUTION_PRIME_ERROR) \
      ENUM_AS_STRING_IF_EQ(r, CHANNEL_CLAMP_ERROR) \
      ENUM_AS_STRING_IF_EQ(r, METERED_SOLUTION_ENDED_BY_OPERATOR) \
      ENUM_AS_STRING_IF_EQ(r, TRIPLE_PPC_AS_NON_LEUKOREDUCED) \
      ENUM_AS_STRING_IF_EQ(r, LAST_REASON) \
      "UNKNOWN_REASON" \
   )
#endif // PQMONITOR_BASE

#endif // ____VerifyFlags__

/* FORMAT HASH 1e2d5c92c87da287ed4c3936955fdd15 */
