// List of all object ID's used in the Barcode Screen
//
#ifndef BC_OBJECT_NAME_H
#define BC_OBJECT_NAME_H

enum BC_OBJECT_NAME
{
   CARTOUCHE_INPUT,
   CARTOUCHE_CATEGORY,
   BTN_RESET_INPUT,
   BTN_RESET_CATEGORY,
   CATEGORY_BTN_COLLECTION,
   BTN_CATEGORY_MORE_1,
   BTN_CATEGORY_MORE_2
} ;

#endif

/* FORMAT HASH 333606eb1bee82adc1f0f58985fa92ee */
