// Single include define guardian
#ifndef SYSDNINC_H
#define SYSDNINC_H



// These are the types of SYSDONOR state components that contribute to the overall
//  SYSDONOR "state"

enum SD_EVENT_TYPE
{
   SD_DISPLAY_LOAD_SYSTEM,
   SD_ENABLE_BEGIN_RUN,
   SD_AP2_IN_CONTROL,
   SD_AP2_DONOR_DATA_AVAILABILITY,
   SD_SCREEN_DISPLAY_STATE
};



// SYSDONOR_OBJECT ENUM - the enumerations of the screen objects that the micro-executes
//  can act upon.

enum SYSDONOR_OBJECT
{
   SD_STATUSLINE,

   SD_STATUSBAR,

   SD_ENDRUN_BTN,
   SD_CONFIG_BTN,
   SD_CONTINUE_BTN,
   SD_LOADSYS_BTN,
   SD_DONORINFO_BTN,

   SD_GENERAL_FUNC
};



// SYSDONOR_OP ENUM - the enumerations of the actions that can be performed on the
//  screen objects.

enum SYSDONOR_OP
{
   SDOP_STATUSLINE_RESET,
   SDOP_STATUSLINE_DEACTIVATE_ATTENTION,
   SDOP_STATUSLINE_SET_COLOR,
   SDOP_STATUSLINE_SET_TEXT,
   SDOP_STATUSLINE_LOAD_DONOR_NAME,

   SDOP_STATUSBAR_RESET_ALL_PHASES,
   SDOP_STATUSBAR_SET_PHASE_COMPLETE,
   SDOP_STATUSBAR_SET_PHASE_ACTIVE,

   SDOP_BUTTON_SET_VISIBLE,
   SDOP_BUTTON_SET_INVISIBLE,
   SDOP_BUTTON_SET_ACTIVE,
   SDOP_BUTTON_SET_INACTIVE,
   SDOP_BUTTON_SET_UP_BITMAP,
   SDOP_BUTTON_SET_DN_BITMAP,
   SDOP_BUTTON_SET_TEXT,
   SDOP_BUTTON_SET_TEXT_COLOR,

   SDOP_BUTTON_SYSLOAD_ALL_COL_UNCHK_ACT,
   SDOP_BUTTON_SYSLOAD_ALL_GRY_CHKED_INACT,
   SDOP_BUTTON_SYSLOAD_INVISIBLE,
   SDOP_BUTTON_DONINFO_MAN_COL_UNCHK_ACT,
   SDOP_BUTTON_DONINFO_MAN_COL_CHKED_ACT,
   SDOP_BUTTON_DONINFO_AP2_GRY_UNCHK_INACT,
   SDOP_BUTTON_DONINFO_AP2_COL_UNCHK_ACT,
   SDOP_BUTTON_DONINFO_AP2_COL_CHKED_ACT,
   SDOP_BUTTON_ENDRUN_ACTIVATE,
   SDOP_BUTTON_CONFIG_ACTIVATE,
   SDOP_BUTTON_BEGINRUN_ACTIVATE,

   SDOP_GENERAL_GOTO_SCREEN,
   SDOP_GENERAL_FREEZE_SCREEN
};




// The Logical eumerations for states
enum SD_T_F_D
{
   SD_FALSE,
   SD_TRUE,
   SD_DONT_CARE
};


// End of single include define guardian
#endif

/* FORMAT HASH d7ed2e9b7f5e034a92f8e3da6904e8fb */
