1i// This file is auto-generated by the build_string_info utility.
1i// DO NOT EDIT this file directly!
1i
1i#include <vxWorks.h>
1i
1i#include "string_data.h"
1i
s/STRING_FILE_TABLE_START//
s/STRING_FILE_TABLE_END//
s/^\([A-Za-z_][A-Za-z0-9_]*\).*/TrimaTextItem StringData::\1;/p
