1i// This file is auto-generated by the build_string_enum utility.
1i// DO NOT EDIT this file directly!
1i
1i#ifndef __STRING_ID_H__
1i#define __STRING_ID_H__
1i
1ienum TEXT_STRING_ID
1i{
s/STRING_FILE_TABLE_START/TEXT_NULL/
s/STRING_FILE_TABLE_END//
s/^\([A-Za-z_][A-Za-z0-9_]*\).*/   \1,/p
$i\   TEXT_DEF_END
$i};
$i
$i#endif // __STRING_ID_H__
$i
