//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelQuery.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExcelQuery.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;Windows-1252&quot;?&gt;&lt;QuerySerialize xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;&lt;QuerySettings&gt;&lt;DefaultSheetName&gt;Results&lt;/DefaultSheetName&gt;&lt;SwitchSheet&gt;true&lt;/SwitchSheet&gt;&lt;/QuerySettings&gt;&lt;CurrentQueryInfo&gt;&lt;Name&gt;Query Log Info&lt;/Name&gt;&lt;Query&gt;SELECT * FROM LogInfo;&lt;/Query&gt;&lt;TableName&gt;QueryLogInfo&lt;/TableName&gt;&lt;TableGeneration&gt;true&lt;/TableGeneration&gt;&lt;RangeGeneration&gt;true&lt;/RangeGeneration&gt;&lt;/CurrentQueryInfo&gt;&lt;QueryAssetList&gt;&lt;QueryInfo&gt;&lt;Name [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap manager_48x48 {
            get {
                object obj = ResourceManager.GetObject("manager_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;customUI xmlns=&quot;http://schemas.microsoft.com/office/2006/01/customui&quot; loadImage=&quot;GetImage&quot; onLoad=&quot;RibbonLoaded&quot; xmlns:x=&quot;CaridianBCT&quot;&gt;
        ///	&lt;ribbon&gt;
        ///		&lt;tabs&gt;
        ///			&lt;tab idQ=&quot;x:Analysis&quot; label=&quot;Analysis&quot;&gt;
        ///				&lt;group id=&quot;QueryManager&quot; label=&quot;Extended Query&quot;&gt;
        ///					&lt;button id=&quot;QueryButton&quot; label=&quot;Query&quot; image=&quot;search-48x48.png&quot; size=&quot;large&quot; onAction=&quot;QueryWorksheet&quot; /&gt;
        ///					&lt;button id=&quot;ManagerButton&quot; label=&quot;Manager&quot; image=&quot;manager-48x48.png&quot; size=&quot;large&quot; onAction=&quot;SearchManager&quot; /&gt;
        ///					&lt;button id=&quot;SettingsButton&quot; l [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Ribbon {
            get {
                return ResourceManager.GetString("Ribbon", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap search_48x48 {
            get {
                object obj = ResourceManager.GetObject("search_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap settings_48x48 {
            get {
                object obj = ResourceManager.GetObject("settings_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
