#if !defined(AFX_DONORINPUT_H__623F9A13_B955_11D1_B0F1_006097402E62__INCLUDED_)
#define AFX_DONORINPUT_H__623F9A13_B955_11D1_B0F1_006097402E62__INCLUDED_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CDonorinput wrapper class

class CDonorinput : public CWnd
{
protected:
	DECLARE_DYNCREATE(CDonorinput)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xca3677b6, 0xb507, 0x11d1, { 0xb0, 0xe7, 0x0, 0x60, 0x97, 0x40, 0x2e, 0x62 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	BOOL male();
	BOOL female();
	float precount();
	float safetyTBV();
	float controlTBV();
	BOOL heightIsStandard();
	float height();
	float weight();
	float hematocrit();
	long bloodType();
	BOOL weightIsStandard();
	void SetBloodType(long blood_type);
	void SetHeight(float height);
	void SetHematocrit(float hematocrit);
	void SetWeight(float weight);
	void SetHeightStandard(BOOL height_is_standard);
	void SetWeightStandard(BOOL weight_is_standard);
	void SetMale(BOOL sex_is_male);
	void SetPrecount(float precount);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Developer Studio will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_DONORINPUT_H__623F9A13_B955_11D1_B0F1_006097402E62__INCLUDED_)
