//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by AP2 predictionater.rc
//
#define ID_STOP                         3
#define IDR_AP2PRETYPE_SRVR_IP          4
#define IDR_AP2PRETYPE_SRVR_EMB         5
#define IDR_AP2PRETYPE_CNTR_IP          6
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDP_FAILED_TO_CREATE            102
#define IDP_SOCKETS_INIT_FAILED         104
#define IDS_UNABLE_TO_OPEN_FILE         105
#define IDR_MAINFRAME                   128
#define IDR_AP2PRETYPE                  129
#define IDS_SINGLE_DONOR_15_PRODUCTS_TITLE 130
#define IDS_EXTENDED_RESULTS            131
#define IDD_SINGLE_DONOR_15_PRODUCTS    132
#define IDS_AP2_PREDICTIONATER          133
#define IDD_EXTENDED_RESULTS            134
#define IDS_WHITE                       134
#define IDS_GREY                        135
#define IDS_BLACK                       136
#define IDD_CFG_MAIN                    136
#define IDS_UNKNOWN                     137
#define IDS_CONFIGURATION               138
#define IDD_TEST_SUITE                  138
#define IDS_PRODUCT                     139
#define IDS_REVISION                    140
#define IDS_AUTOMATION_MODEL1_TITLE     141
#define IDC_CURSOR1                     141
#define IDS_TEST_SUITE_TITLE            142
#define IDC_CURSOR2                     142
#define IDS_SINGLE_PRODUCT_TITLE        143
#define IDD_SINGLE_PRODUCT              143
#define IDS_BOBS_MATRIX_TITLE           144
#define IDD_BOBS_MATRIX                 145
#define IDS_INFUSION_TEST_TITLE         145
#define IDD_EDIT_PROCEDURES             146
#define IDS_RP_PLASMA_SUBSTATE          146
#define IDC_CURSOR3                     147
#define IDS_RP_RBC_SETUP_1_SUBSTATE     147
#define IDD_INFUSION_TEST               148
#define IDS_RP_RBC_SETUP_2_SUBSTATE     148
#define IDD_INITIAL_CONDITIONS_DIALOG   149
#define IDS_RP_RBC_SUBSTATE             149
#define IDD_AUTOMATION_MODEL_1          158
#define IDD_ROBUSTNESS                  160
#define IDS_BLOOD_TYPE_AB_NEG           210
#define IDS_BLOOD_TYPE_AB_POS           211
#define IDS_BLOOD_TYPE_B_NEG            212
#define IDS_BLOOD_TYPE_B_POS            213
#define IDS_BLOOD_TYPE_A_NEG            214
#define IDS_BLOOD_TYPE_A_POS            215
#define IDS_BLOOD_TYPE_O_NEG            216
#define IDS_BLOOD_TYPE_O_POS            217
#define IDS_OPTIMIZER_RESULTS_0         257
#define IDS_OPTIMIZER_RESULTS_1         258
#define IDS_OPTIMIZER_RESULTS_2         259
#define IDS_OPTIMIZER_RESULTS_3         260
#define IDS_OPTIMIZER_RESULTS_4         261
#define IDS_OPTIMIZER_RESULTS_5         262
#define IDS_OPTIMIZER_RESULTS_6         263
#define IDS_OPTIMIZER_RESULTS_7         264
#define IDS_OPTIMIZER_RESULTS_8         265
#define IDS_OPTIMIZER_RESULTS_9         266
#define IDS_OPTIMIZER_RESULTS_10        267
#define IDS_OPTIMIZER_RESULTS_11        268
#define IDS_OPTIMIZER_RESULTS_12        269
#define IDS_OPTIMIZER_RESULTS_13        270
#define IDS_OPTIMIZER_RESULTS_14        271
#define IDS_OPTIMIZER_RESULTS_15        272
#define IDS_OPTIMIZER_RESULTS_16        273
#define IDS_OPTIMIZER_RESULTS_17        274
#define IDS_OPTIMIZER_RESULTS_18        275
#define IDS_OPTIMIZER_RESULTS_19        276
#define IDS_OPTIMIZER_RESULTS_QIN_BELOW_SPEC 277
#define IDS_OPTIMIZER_RESULTS_INCORRECT_DESIGNATOR 278
#define IDS_OPTIMIZER_RESULTS_21        278
#define IDS_OPTIMIZER_RESULTS_UNOPTIMIZED 279
#define IDS_OPTIMIZER_RESULTS_22        279
#define IDS_OPTIMIZER_RESULTS_23        280
#define IDS_OPTIMIZER_RESULTS_24        281
#define IDS_OPTIMIZER_RESULTS_25        282
#define IDS_OPTIMIZER_RESULTS_26        283
#define IDC_DONORINPUTCTRL              1000
#define IDC_TBV_VOLUME                  1001
#define IDC_VOLUME_LESS_THAN            1002
#define IDC_VOLUME_GREATER_THAN         1003
#define IDC_COLLCOUNT_EDIT              1003
#define IDC_PERCENT_TBV                 1004
#define IDC_WB_RBC_NOLOSS_EDIT          1004
#define IDC_REMOVE_WEIGHT               1005
#define IDC_WB_FFP_NOLOSS_EDIT          1005
#define IDC_RATIO_START                 1006
#define IDC_WB_PLT_NOLOSS_EDIT          1006
#define IDC_ML_PER_KG                   1006
#define IDC_RATIO_END                   1007
#define IDC_WB_FRACP_NOLOSS_EDIT        1007
#define IDC_INFUSION_START              1007
#define IDC_RATIO_TIME                  1008
#define IDC_WB_RECLOSS_EDIT             1008
#define IDC_DRAW_FLOW_START             1008
#define IDC_LOAD_FILE                   1009
#define IDC_AUTO_RECLOSS_EDIT           1009
#define IDC_DRAW_MANAGEMENT_START       1009
#define IDC_SAVE_FILE                   1010
#define IDC_WB_COLLLOSS_EDIT            1010
#define IDC_RETURN_MANAGEMENT_START     1010
#define IDC_PLT2_YIELD                  1011
#define IDC_AUTO_COLLLOSS_EDIT          1011
#define IDC_RESULTS                     1011
#define IDC_PLT1_VOLUME                 1012
#define IDC_WB_CLABLOSS_EDIT            1012
#define IDC_CONFIG                      1012
#define IDC_INLET_RAMP_START            1012
#define IDC_PLT1_CONCENTRATION          1013
#define IDC_AUTO_CLABLOSS_EDIT          1013
#define IDC_PTF_START                   1013
#define IDC_PLT1_YIELD                  1014
#define IDC_WB_TLABLOSS_EDIT            1014
#define IDC_PLT2_VOLUME                 1015
#define IDC_AUTO_TLABLOSS_EDIT          1015
#define IDC_PLT2_CONCENTRATION          1016
#define IDC_WB_DISTLOSS_EDIT            1016
#define IDC_OPTIMIZE                    1017
#define IDC_PLT3_YIELD                  1017
#define IDC_AUTO_DISTLOSS_EDIT          1017
#define IDC_PLT3_VOLUME                 1018
#define IDC_WB_OUTDATELOSS_EDIT         1018
#define IDC_INITIAL_CONDITIONS          1018
#define IDC_PLT3_CONCENTRATION          1019
#define IDC_AUTO_OUTDATELOSS_EDIT       1019
#define IDC_EXTENDED_RESULTS            1019
#define IDC_YSF                         1020
#define IDC_WB_RBC_NETTTL_EDIT          1020
#define IDC_PRODUCT_PLASMA_1            1021
#define IDC_WB_FFP_NETTTL_EDIT          1021
#define IDC_PRODUCT_PLT_1               1022
#define IDC_WB_PLT_NETTTL_EDIT          1022
#define IDC_RBC_YSF                     1022
#define IDC_PRODUCT_RBC_1               1023
#define IDC_WB_FRACP_NETTTL_EDIT        1023
#define IDC_RESULTS_LIST                1024
#define IDC_AUTO_RBC_NOLOSS_EDIT        1024
#define IDC_PRODUCT_BLOOD_TYPE_1        1024
#define IDC_PRODUCT_PLASMA_2            1025
#define IDC_AUTO_FFP_NOLOSS_EDIT        1025
#define IDC_DONOR_BLOOD_TYPE            1025
#define IDC_PRODUCT_PLT_2               1026
#define IDC_AUTO_PLT_NOLOSS_EDIT        1026
#define IDC_PRODUCT_BLOOD_TYPE_2        1026
#define IDC_PRODUCT_RBC_2               1027
#define IDC_AUTO_FRACP_NOLOSS_EDIT      1027
#define IDC_AUTO_RBC_NETTTL_EDIT        1028
#define IDC_PRODUCT_BLOOD_TYPE_3        1028
#define IDC_PRODUCT_PLASMA_3            1029
#define IDC_AUTO_FFP_NETTTL_EDIT        1029
#define IDC_PRODUCT_PLT_3               1030
#define IDC_AUTO_SDP_NETTTL_EDIT        1030
#define IDC_PRODUCT_BLOOD_TYPE_4        1030
#define IDC_PRODUCT_RBC_3               1031
#define IDC_AUTO_FRACP_NETTTL_EDIT      1031
#define IDC_DRBC_FOCUS_RB               1032
#define IDC_PRODUCT_BLOOD_TYPE_5        1032
#define IDC_CONFIGURED_YIELD            1033
#define IDC_PRODUCT_PLASMA_4            1033
#define IDC_RBC_FOCUS_RB                1033
#define IDC_CONFIGURED_PLATELETS        1034
#define IDC_PRODUCT_PLT_4               1034
#define IDC_PLT_FOCUS_RB                1034
#define IDC_PRODUCT_BLOOD_TYPE_6        1034
#define IDC_CONFIGURED_CONCENTRATION    1035
#define IDC_PRODUCT_RBC_4               1035
#define IDC_PLASMA_FOCUS_RB             1035
#define IDC_CONFIGURED_PLASMA           1036
#define IDC_DONORDB_COMBO               1036
#define IDC_PRODUCT_BLOOD_TYPE_7        1036
#define IDC_CONFIGURED_RBCS             1037
#define IDC_PRODUCT_PLASMA_5            1037
#define IDC_MANU_SIM_PB                 1037
#define IDC_YIELD_IN_SPEC               1038
#define IDC_PRODUCT_PLT_5               1038
#define IDC_AUTO_CHOICE_1_EDIT          1038
#define IDC_PRODUCT_BLOOD_TYPE_8        1038
#define IDC_CONCENTRATION_IN_SPEC       1039
#define IDC_PRODUCT_RBC_5               1039
#define IDC_AUTO_CHOICE_2_EDIT          1039
#define IDC_PLASMA_IN_SPEC              1040
#define IDC_AUTO_CHOICE_3_EDIT          1040
#define IDC_PRODUCT_BLOOD_TYPE_9        1040
#define IDC_RBCS_IN_SPEC                1041
#define IDC_PRODUCT_PLASMA_6            1041
#define IDC_AUTO_CHOICE_4_EDIT          1041
#define IDC_ACTUAL_PLATELETS            1042
#define IDC_PRODUCT_PLT_6               1042
#define IDC_AUTO_CHOICE_5_EDIT          1042
#define IDC_PRODUCT_BLOOD_TYPE_10       1042
#define IDC_ACTUAL_YIELD                1043
#define IDC_PRODUCT_RBC_6               1043
#define IDC_AUTO_CHOICE_6_EDIT          1043
#define IDC_ACTUAL_CONCENTRATION        1044
#define IDC_AUTO_CHOICE_7_EDIT          1044
#define IDC_PRODUCT_BLOOD_TYPE_11       1044
#define IDC_ACTUAL_PLASMA               1045
#define IDC_PRODUCT_PLASMA_7            1045
#define IDC_AUTO_CHOICE_8_EDIT          1045
#define IDC_ACTUAL_RBCS                 1046
#define IDC_PRODUCT_PLT_7               1046
#define IDC_AUTO_CHOICE_9_EDIT          1046
#define IDC_PRODUCT_BLOOD_TYPE_12       1046
#define IDC_REMAINING_VOLUME            1047
#define IDC_PRODUCT_RBC_7               1047
#define IDC_AUTO_CHOICE_10_EDIT         1047
#define IDC_CASSETTE                    1048
#define IDC_AUTO_CHOICE_11_EDIT         1048
#define IDC_PRODUCT_BLOOD_TYPE_13       1048
#define IDC_TIME_STARTUP                1049
#define IDC_PRODUCT_PLASMA_8            1049
#define IDC_AUTO_CHOICE_12_EDIT         1049
#define IDC_TIME_PLATELET               1050
#define IDC_PRODUCT_PLT_8               1050
#define IDC_AUTO_CHOICE_13_EDIT         1050
#define IDC_PRODUCT_BLOOD_TYPE_14       1050
#define IDC_TIME_PLT_PLASMA             1051
#define IDC_PRODUCT_RBC_8               1051
#define IDC_AUTO_CHOICE_14_EDIT         1051
#define IDC_TIME_PREPIR                 1052
#define IDC_AUTO_CHOICE_15_EDIT         1052
#define IDC_PRODUCT_BLOOD_TYPE_15       1052
#define IDC_TIME_PIR                    1053
#define IDC_PRODUCT_PLASMA_9            1053
#define IDC_OPT_PROGRESS                1053
#define IDC_TIME_RBC_PLASMA             1054
#define IDC_PRODUCT_PLT_9               1054
#define IDC_AUTO_CHOICE_11_EDIT2        1054
#define IDC_PRODUCT_BLOOD_TYPE_16       1054
#define IDC_TIME_PLASMA                 1055
#define IDC_PRODUCT_RBC_9               1055
#define IDC_AUTO_CHOICE_12_EDIT2        1055
#define IDC_TIME_RBC                    1056
#define IDC_AUTO_CHOICE_13_EDIT2        1056
#define IDC_MAX_DRAW_FLOW               1056
#define IDC_VBP_STARTUP                 1057
#define IDC_PRODUCT_PLASMA_10           1057
#define IDC_AUTO_CHOICE_14_EDIT2        1057
#define IDC_TARGET_PLATELETS            1057
#define IDC_PPC_MOD                     1057
#define IDC_VIN_STARTUP                 1058
#define IDC_PRODUCT_PLT_10              1058
#define IDC_AUTO_CHOICE_15_EDIT2        1058
#define IDC_PRODUCT_BLOOD_TYPE_17       1058
#define IDC_VAC_STARTUP                 1059
#define IDC_PRODUCT_RBC_10              1059
#define IDC_AUTO_CHOICE_6_EDIT2         1059
#define IDC_VBP_PLATELET                1060
#define IDC_AUTO_CHOICE_7_EDIT2         1060
#define IDC_PRODUCT_BLOOD_TYPE_18       1060
#define IDC_VIN_PLATELET                1061
#define IDC_PRODUCT_PLASMA_11           1061
#define IDC_AUTO_CHOICE_8_EDIT2         1061
#define IDC_VAC_PLATELET                1062
#define IDC_PRODUCT_PLT_11              1062
#define IDC_AUTO_CHOICE_9_EDIT2         1062
#define IDC_PRODUCT_BLOOD_TYPE_19       1062
#define IDC_VBP_PLT_PLASMA              1063
#define IDC_PRODUCT_RBC_11              1063
#define IDC_AUTO_CHOICE_10_EDIT2        1063
#define IDC_VIN_PLT_PLASMA              1064
#define IDC_AUTO_CHOICE_1_EDIT2         1064
#define IDC_PRODUCT_BLOOD_TYPE_20       1064
#define IDC_VAC_PLT_PLASMA              1065
#define IDC_PRODUCT_PLASMA_12           1065
#define IDC_AUTO_CHOICE_2_EDIT2         1065
#define IDC_VBP_PREPIR                  1066
#define IDC_PRODUCT_PLT_12              1066
#define IDC_AUTO_CHOICE_3_EDIT2         1066
#define IDC_VIN_PREPIR                  1067
#define IDC_PRODUCT_RBC_12              1067
#define IDC_AUTO_CHOICE_4_EDIT2         1067
#define IDC_VAC_PREPIR                  1068
#define IDC_AUTO_CHOICE_5_EDIT2         1068
#define IDC_VBP_PIR                     1069
#define IDC_PRODUCT_PLASMA_13           1069
#define IDC_STOP_SIM_PB                 1069
#define IDC_VIN_PIR                     1070
#define IDC_PRODUCT_PLT_13              1070
#define IDC_EDIT_CONFIG                 1070
#define IDC_VAC_PIR                     1071
#define IDC_PRODUCT_RBC_13              1071
#define IDC_PRODUCT_PLATELET            1071
#define IDC_START                       1071
#define IDC_VBP_RBC_PLASMA              1072
#define IDC_PRODUCT_PLATELET_PLASMA     1072
#define IDC_STOP                        1072
#define IDC_VIN_RBC_PLASMA              1073
#define IDC_PRODUCT_PLASMA_14           1073
#define IDC_PRODUCT_PLATELET_PLASMA_RBCS 1073
#define IDC_VAC_RBC_PLASMA              1074
#define IDC_PRODUCT_PLT_14              1074
#define IDC_PRODUCT_PLATELET_RBCS       1074
#define IDC_VBP_PLASMA                  1075
#define IDC_PRODUCT_RBC_14              1075
#define IDC_PRODUCT_PLASMA_RBCS         1075
#define IDC_VIN_PLASMA                  1076
#define IDC_PRODUCT_RBCS                1076
#define IDC_VAC_PLASMA                  1077
#define IDC_PRODUCT_PLASMA_15           1077
#define IDC_PRODUCT_PLASMA              1077
#define IDC_VBP_RBC                     1078
#define IDC_PRODUCT_PLT_15              1078
#define ID_START                        1078
#define IDC_PRODUCT_PLASMA_16           1078
#define IDC_VIN_RBC                     1079
#define IDC_PRODUCT_RBC_15              1079
#define IDC_QRP_ADJUSTMENT              1079
#define IDC_VAC_RBC                     1080
#define IDC_QIN_LIMIT                   1080
#define IDC_PRODUCT_RBC_16              1080
#define IDC_AC_PLATELET                 1081
#define IDC_LANGUAGE                    1081
#define IDC_TOTAL_PRODUCTS              1081
#define IDC_PLT5_YIELD                  1081
#define IDC_AC_PLASMA                   1082
#define IDC_HEIGHT_UNITS                1082
#define IDC_TEST_SUITE_PROGRESS         1082
#define IDC_AC_RBC                      1083
#define IDC_WEIGHT_UNITS                1083
#define IDC_PERCENT_COMPLETE            1083
#define IDC_PLASMA_SMALL                1084
#define IDC_TOTAL_GOOD                  1084
#define IDC_GOOD_LT_2000                1084
#define IDC_PLASMA_1                    1084
#define IDC_CONFIGURED_MAX_TIME         1085
#define IDC_PLASMA_MEDIUM               1085
#define IDC_TEST_SUBSTATE               1085
#define IDC_UNCONVERGED_LT_2000         1085
#define IDC_PLASMA_2                    1085
#define IDC_ACTUAL_MAX_TIME             1086
#define IDC_PLASMA_LARGE                1086
#define IDC_TOTAL_TRIED                 1086
#define IDC_PLASMA_3                    1086
#define IDC_CONFIGURED_BLOOD_TYPE       1087
#define IDC_PLASMA_AMAP                 1087
#define IDC_GOOD_PLASMA                 1087
#define IDC_PERCENT_LT_2000             1087
#define IDC_PLASMA_AMAP_MIN             1087
#define IDC_ACTUAL_BLOOD_TYPE           1088
#define IDC_MAX_PROCEDURE_TIME          1088
#define IDC_GOOD_RBCS                   1088
#define IDC_GOOD_LT_4000                1088
#define IDC_MINIMUM_POSTCOUNT           1089
#define IDC_GOOD_PLASMA_RBCS            1089
#define IDC_CONFIGURED_REPLACEMENT_VOLUME 1089
#define IDC_UNCONVERGED_LT_4000         1089
#define IDC_GOOD_PLATELETS_RBCS         1090
#define IDC_ACTUAL_REPLACEMENT_VOLUME   1090
#define IDC_RBC_RATIO                   1090
#define IDC_PERCENT_LT_4000             1090
#define IDC_GOOD_PLATELETS_PLASMA_RBCS  1091
#define IDC_REPLACEMENT_FLUID           1091
#define IDC_GOOD                        1091
#define IDC_MINIMUM_POSTCRIT            1092
#define IDC_GOOD_PLATELETS_PLASMA       1092
#define IDC_VOLUME_FROM_DONOR           1092
#define IDC_UNCONVERGED                 1092
#define IDC_INFUSION_RATE               1093
#define IDC_GOOD_PLATELETS              1093
#define IDC_PERCENT_GOOD                1093
#define IDC_RBC_COLLECT_VOLUME          1094
#define IDC_TOTAL_PLASMA                1094
#define IDC_RBC_COLLECT_VOLUME_1        1094
#define IDC_GOOD_GT_4000                1094
#define IDC_RBC_CRIT                    1095
#define IDC_TOTAL_RBCS                  1095
#define IDC_RBC_CRIT_1                  1095
#define IDC_UNCONVERGED_GT_4000         1095
#define IDC_RBC_DOSE                    1096
#define IDC_TOTAL_PLASMA_RBCS           1096
#define IDC_RBC_DOSE_1                  1096
#define IDC_PERCENT_GT_4000             1096
#define IDC_TOTAL_PLATELETS_RBCS        1097
#define IDC_RBC_COLLECT_VOLUME_CUSTOM   1097
#define IDC_RBC_COLLECT_VOLUME_2        1097
#define IDC_INCONC_PERCENT_LT_2000      1097
#define IDC_TOTAL_PLATELETS_PLASMA_RBCS 1098
#define IDC_RBC_CRIT_CUSTOM             1098
#define IDC_RBC_CRIT_2                  1098
#define IDC_INCONC_PERCENT_LT_4000      1098
#define IDC_TOTAL_PLATELETS_PLASMA      1099
#define IDC_RBC_DOSE_CUSTOM             1099
#define IDC_RBC_DOSE_2                  1099
#define IDC_INCONC_PERCENT_GOOD         1099
#define IDC_TOTAL_PLATELETS             1100
#define IDC_REPLACEMENT_FLUID_PERCENT   1100
#define IDC_INCONC_PERCENT_GT_4000      1100
#define IDC_REMAINING_TIME              1101
#define IDC_RBC_COLLECT_VOLUME_3        1101
#define IDC_DONORINPUTCTRL1             1102
#define IDC_ITERATIONS_TOTAL            1102
#define IDC_RBC_CRIT_3                  1102
#define IDC_INCONC_LT_2000              1102
#define IDC_ITERATIONS_PLASMA           1103
#define IDC_RBC_DOSE_3                  1103
#define IDC_TOTAL_ITERATIONS            1103
#define IDC_INCONC_LT_4000              1103
#define IDC_SAVE_PATH                   1104
#define IDC_ITERATIONS_RBCS             1104
#define IDC_PLT4_VOLUME                 1104
#define IDC_INCONC                      1104
#define IDC_INTERMEDIATE_RESULTS        1105
#define IDC_ITERATIONS_PLASMA_RBCS      1105
#define IDC_PLT4_CONCENTRATION          1105
#define IDC_INCONC_GT_4000              1105
#define IDC_SAVE_CONFIG_DATA            1106
#define IDC_ITERATIONS_PLATELETS_RBCS   1106
#define IDC_PLT4_YIELD                  1106
#define IDC_SAVE_DATA_TO                1107
#define IDC_ITERATIONS_PLATELETS_PLASMA_RBCS 1107
#define IDC_PLT5_VOLUME                 1107
#define IDC_PPC_MOD_LT_2000             1107
#define IDC_ITERATIONS_PLATELETS_PLASMA 1108
#define IDC_PLT5_CONCENTRATION          1108
#define IDC_PPC_MOD_LT_4000             1108
#define IDC_FIRST_TO_TRY                1109
#define IDC_PLT6_YIELD                  1109
#define IDC_PPC_MOD_GT_4000             1109
#define IDC_ITERATIONS_PLATELETS        1110
#define IDC_PLT6_VOLUME                 1110
#define IDC_ELAPSED_TIME                1111
#define IDC_PLT6_CONCENTRATION          1111
#define IDC_PRODUCT_PLATELET_1          1112
#define IDC_MAX_ITERATIONS_AMAP_PLT     1113
#define IDC_PRODUCT_PLATELET_2          1113
#define IDC_MAX_ITERATIONS_AMAP_PLT_PL  1114
#define IDC_LOAD_DONOR_DB               1114
#define IDC_PRODUCT_PLATELET_3          1114
#define IDC_MAX_ITERATIONS_AMAP_PLT_PL_RBC 1115
#define IDC_DONORDB_FILENAME            1115
#define IDC_PRODUCT_PLATELET_4          1115
#define IDC_MAX_ITERATIONS_AMAP_PLT_RBC 1116
#define IDC_STATUS_LINE                 1116
#define IDC_PRODUCT_PLATELET_5          1116
#define IDC_MAX_ITERATIONS_AMAP_PL_RBC  1117
#define IDC_IC_QIN_ADJUSTMENT           1117
#define IDC_PRODUCT_PLATELET_6          1117
#define IDC_MAX_ITERATIONS_AMAP_RBC     1118
#define IDC_IC_QRP_ADJUSTMENT           1118
#define IDC_PRODUCT_PLATELET_7          1118
#define IDC_MAX_ITERATIONS_AMAP_PL      1119
#define IDC_IC_IR_ADJUSTMENT            1119
#define IDC_PRODUCT_PLATELET_8          1119
#define IDC_MAX_ITERATIONS_PLT          1120
#define IDC_IC_RATIO_ADJUSTMENT         1120
#define IDC_PRODUCT_PLATELET_9          1120
#define IDC_MAX_ITERATIONS_PLT_PL       1121
#define IDC_IC_COLLECT_BAG_VOLUME       1121
#define IDC_PRODUCT_PLATELET_10         1121
#define IDC_MAX_ITERATIONS_PLT_PL_RBC   1122
#define IDC_IC_PLASMA_BAG_VOLUME        1122
#define IDC_PRODUCT_PLATELET_11         1122
#define IDC_MAX_ITERATIONS_PLT_RBC      1123
#define IDC_IC_RBC_BAG_VOLUME           1123
#define IDC_PRODUCT_PLATELET_12         1123
#define IDC_MAX_ITERATIONS_PL_RBC       1124
#define IDC_IC_COLLECT_BAG_AC           1124
#define IDC_PRODUCT_PLATELET_13         1124
#define IDC_MAX_ITERATIONS_RBC          1125
#define IDC_IC_PLASMA_BAG_AC            1125
#define IDC_PRODUCT_PLATELET_14         1125
#define IDC_MAX_ITERATIONS_PL           1126
#define IDC_IC_RBC_BAG_AC               1126
#define IDC_PRODUCT_PLATELET_15         1126
#define IDC_CONC_PLASMA                 1127
#define IDC_IC_VIN                      1127
#define IDC_REPLACEMENT_VOLUME_TRIGGER  1127
#define IDC_CONC_RBCS                   1128
#define IDC_IC_VAC                      1128
#define IDC_CUSTOM_RATIO                1128
#define IDC_CONC_PLASMA_RBCS            1129
#define IDC_IC_VP                       1129
#define IDC_DRAW_MANAGEMENT             1129
#define IDC_CONC_PLATELETS_RBCS         1130
#define IDC_IC_VCOL                     1130
#define IDC_RETURN_MANAGEMENT           1130
#define IDC_CONC_PLATELETS_PLASMA_RBCS  1131
#define IDC_IC_VREP                     1131
#define IDC_INLET_RAMP                  1131
#define IDC_CONC_PLATELETS_PLASMA       1132
#define IDC_IC_VRP                      1132
#define IDC_PLASMA_AMAP_MAX             1132
#define IDC_CONC_PLATELETS              1133
#define IDC_IC_QIN                      1133
#define IDC_PLASMA_4                    1133
#define IDC_CONC_TOTAL                  1134
#define IDC_IC_QAC                      1134
#define IDC_PLASMA_5                    1134
#define IDC_IC_QP                       1135
#define IDC_PLASMA_6                    1135
#define IDC_IC_QCOL                     1136
#define IDC_PLASMA_RINSEBACK            1136
#define IDC_IC_QREP                     1137
#define IDC_PRODUCT_PLATELET_16         1137
#define IDC_IC_QRP                      1138
#define IDC_PRODUCT_PLATELET_17         1138
#define IDC_IC_RPM                      1139
#define IDC_PRODUCT_PLASMA_17           1139
#define IDC_IC_PREPIR_PROCESSED_VOLUME  1140
#define IDC_IC_RBC_BAG_DOSE             1140
#define IDC_PRODUCT_RBC_17              1140
#define IDC_IC_PIR_PROCESSED_VOLUME     1141
#define IDC_IC_VBOLUS                   1141
#define IDC_PRODUCT_PLATELET_18         1141
#define IDC_IC_RBC_SETUP_PROCESSED_VOLUME 1142
#define IDC_PRODUCT_PLASMA_18           1142
#define IDC_IC_VBP_PLATELET             1143
#define IDC_PRODUCT_RBC_18              1143
#define IDC_IC_SOURCE_PLASMA_ENTERED    1144
#define IDC_PRODUCT_PLATELET_19         1144
#define IDC_IC_PLTCONCBAG               1145
#define IDC_PRODUCT_PLASMA_19           1145
#define IDC_IC_YIELD                    1146
#define IDC_START_SIMULATION            1146
#define IDC_PRODUCT_RBC_19              1146
#define IDC_IC_PROCEDURE_RUN_TIME       1147
#define IDC_STOP_SIMULATION             1147
#define IDC_PRODUCT_PLATELET_20         1147
#define IDC_IC_SUBSTATE                 1148
#define IDC_PRODUCT_TIME_1              1148
#define IDC_IC_SYSTEM_STATE             1149
#define IDC_PRODUCT_TIME_2              1149
#define IDC_IC_TCV                      1149
#define IDC_PRODUCT_TIME_3              1150
#define IDC_IC_CASSETTE                 1150
#define IDC_PRODUCT_TIME_4              1151
#define IDC_IC_MINIMUM_QCH              1151
#define IDC_PRODUCT_TIME_5              1152
#define IDC_IC_CURRENT_QCH              1152
#define IDC_PRODUCT_TIME_6              1153
#define IDC_IC_PURGES                   1153
#define IDC_PRODUCT_TIME_7              1154
#define IDC_DONOR_HEIGHT                1154
#define IDC_IC_EPCA_START               1154
#define IDC_PRODUCT_TIME_8              1155
#define IDC_DONOR_WEIGHT                1155
#define IDC_IC_VINCV                    1155
#define IDC_PRODUCT_TIME_9              1156
#define IDC_DONOR_PRECOUNT              1156
#define IDC_PTF                         1156
#define IDC_PRODUCT_TIME_10             1157
#define IDC_DONOR_HEMATOCRIT            1157
#define IDC_PTF_QRBC                    1157
#define IDC_PRODUCT_TIME_11             1158
#define IDC_CALCULATED_TBV              1158
#define IDC_DONOR_HEIGHT2               1158
#define IDC_PRODUCT_TIME_12             1159
#define IDC_DONOR_WEIGHT2               1159
#define IDC_PRODUCT_TIME_13             1160
#define IDC_DONOR_PRECOUNT2             1160
#define IDC_PRODUCT_TIME_14             1161
#define IDC_DONOR_HEMATOCRIT2           1161
#define IDC_PRODUCT_TIME_15             1162
#define IDC_CALCULATED_TBV2             1162
#define IDC_PRODUCT_TIME_16             1163
#define IDC_PRODUCT_TIME_17             1164
#define IDC_PRODUCT_TIME_18             1165
#define IDC_HEIGHT_IN                   1166
#define IDC_PRODUCT_TIME_19             1166
#define IDC_HEIGHT_CM                   1167
#define IDC_PRODUCT_PLASMA_20           1167
#define IDC_WEIGHT_LB                   1168
#define IDC_PRODUCT_RBC_20              1168
#define IDC_WEIGHT_KG                   1169
#define IDC_PRODUCT_TIME_20             1169
#define IDC_MALE                        1170
#define IDC_SALINE_RINSEBACK1           1170
#define IDC_SALINE_RINSEBACK            1170
#define IDC_FEMALE                      1171
#define IDC_ENABLE_DEBUG                1175
#define IDC_DONOR_DB                    1179
#define IDC_TBV_LIMIT_ACTIVE            1180
#define IDC_VOLUME_LIMIT_ACTIVE         1181
#define IDC_IC_RUNDATA_FILE             1181
#define IDC_ML_PER_KG_LIMIT_ACTIVE      1182
#define IDC_IC_SNARF                    1182
#define IDC_IC_ABSTIME                  1183
#define IDC_IC_BROWSE                   1184
#define IDC_HCT_START                   1184
#define IDC_IC_RESET                    1185
#define IDC_PRECOUNT_START              1185
#define IDC_HCT_STOP                    1186
#define IDC_IC_COBE_CONFIG_FILE         1186
#define IDC_TBV_START                   1187
#define IDC_PRECOUNT_STOP               1188
#define IDC_TBV_STOP                    1189
#define IDC_HCT_TESTS                   1190
#define IDC_PRECOUNT_TESTS              1191
#define IDC_TBV_TESTS                   1192
#define IDC_YIELD_START                 1193
#define IDC_PLASMA_START                1194
#define IDC_YIELD_STOP                  1195
#define IDC_RBCDOSE_START               1196
#define IDC_PLASMA_STOP                 1197
#define IDC_RBCDOSE_STOP                1198
#define IDC_YIELD_TESTS                 1199
#define IDC_PLASMA_TESTS                1200
#define IDC_RBCDOSE_TESTS               1201
#define IDC_RBCCRIT_START               1202
#define IDC_RBCCRIT_STOP                1203
#define IDC_RBCCRIT_TESTS               1204
#define IDC_YIELD_DELTA                 1205
#define IDC_PLASMA_DELTA                1206
#define IDC_RBCDOSE_DELTA               1207
#define IDC_RBCCRIT_DELTA               1208
#define IDC_HCT_DELTA                   1209
#define IDC_PRECOUNT_DELTA              1210
#define IDC_TBV_DELTA                   1211
#define IDC_CONC_START                  1212
#define IDC_CONC_STOP                   1213
#define IDC_CONC_TESTS                  1214
#define IDC_CONC_DELTA                  1215
#define IDC_AMAP                        1225
#define IDC_MAX_CONCURRENT              1226
#define IDC_RATIO_STOP                  1227
#define IDC_RATIO_DELTA                 1228
#define IDC_INFUSION_STOP               1229
#define IDC_INFUSION_DELTA              1230
#define IDC_DRAW_FLOW_STOP              1231
#define IDC_DRAW_FLOW_DELTA             1232
#define IDC_DRAW_MANAGEMENT_STOP        1233
#define IDC_DRAW_MANAGEMENT_DELTA       1234
#define IDC_RETURN_MANAGEMENT_STOP      1235
#define IDC_RETURN_MANAGEMENT_DELTA     1236
#define IDC_INLET_RAMP_STOP             1237
#define IDC_INLET_RAMP_DELTA            1238
#define IDC_CONVERGENCE                 1252
#define IDC_DISPLAY_UNCONVERGED         1253
#define IDC_DISPLAY_VC_ERRS             1254
#define IDC_DISPLAY_CONCENTRATION       1255
#define IDC_DISPLAY_VP_ERRS             1256
#define IDC_DISPLAY_CHAMBER_FLOW        1257
#define IDC_LOCKIN_ERRORS               1258
#define IDC_DISPLAY_LOCKIN              1259
#define IDC_DEBUG                       1260
#define IDC_REPREDICT                   1261
#define IDC_RESTORE_OUTPUT              1262
#define IDC_SAVE_OUTPUT                 1263
#define IDC_LISTBOX_SAVE_PATH           1264
#define IDC_SEQUENTIAL                  1265
#define IDC_USE_NORMAL                  1266
#define IDC_CHECK1                      1266
#define IDC_COMPARE_V5                  1267
#define IDC_ADJUST_RANDOM               1268
#define IDC_SEND_PREDICT_REQUEST        1269
#define IDC_PREDICT_REQUEST             1270
#define IDC_IC_COBE_CONFIG              1280
#define IDC_IC_LOAD_CSV_FILE            1281
#define IDC_RADIO_Small                 1282
#define IDC_RADIO_Medium                1283
#define IDC_RADIO_Large                 1284
#define IDC_RADIO_Male                  1285
#define IDC_MSS_RBC1_CHECK              1286
#define IDC_RBC_MSS_CHECK1              1286
#define IDC_RADIO_Female                1287
#define IDC_MSS_RBC_CHECK2              1287
#define IDC_RBC_MSS_CHECK2              1287
#define IDC_MSS_RBC1_CHECK3             1288
#define IDC_RBC_MSS_CHECK3              1288
#define IDC_PLT_CHECK1                  1290
#define IDC_PLT_MSS_CHECK1              1290
#define IDC_PLT_CHECK2                  1291
#define IDC_PLT_MSS_CHECK2              1291
#define IDC_PLT_CHECK3                  1292
#define IDC_PLT_MSS_CHECK3              1292
#define IDC_PLT_CHECK4                  1293
#define IDC_PLT_MSS_CHECK4              1293
#define IDC_PLT_CHECK5                  1294
#define IDC_PLT_MSS_CHECK5              1294
#define IDC_PLT_CHECK6                  1295
#define IDC_PLT_MSS_CHECK6              1295
#define ID_CANCEL_EDIT_CNTR             32768
#define ID_CANCEL_EDIT_SRVR             32769
#define ID_OPTIMIZER_SINGLEDONOR15PRODUCT 32775
#define ID_REVISION_TRIMA_3_1_USA       32777
#define ID_CONFIG_TRIMA                 32778
#define ID_REVISION_TRIMA_3_2           32780
#define ID_REVISION_TRIMA_3_1_OUTSIDEUSA 32781
#define ID_OPTIMIZER_TEST_SUITE         32782
#define ID_OPTIMIZER_SINGLEPRODUCT      32783
#define ID_OPTIMIZER_BOBSMATRIX         32785
#define ID_OPTIMIZER_INFUSIONTEST       32787
#define ID_REVISION_TRIMA33             32789
#define ID_OPTIMIZER_DBAUTOMATION       32790
#define ID_OPTIMIZER_DATABASEOPTIMIZER  32791
#define ID_OPTIMIZER_ROBUSTNESS         32792
#define IDC_GRID_1                      32793

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        165
#define _APS_NEXT_COMMAND_VALUE         32794
#define _APS_NEXT_CONTROL_VALUE         1291
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
