// This file is auto-generated by the build_bool_feature_enum.sed utility.
//   DO NOT EDIT this file directly!

#ifndef BOOLEANFEATURES_H_
#define BOOLEANFEATURES_H_

enum FEATURE_ID
{
    EnableScreenshotButton,
    ApsHighSpeedLogEnable,
    CpsHighSpeedLogEnable,
    SelectScreenDisplayPlateletVolume,
    AllowAdjustFlowRatesOnProcedureSelect,
    ConfirmAcConnection,
    DisplayResidualVolumes,
    PostcountPlateletMobilizationAlgorithm,
    AiroutMitigation,
    AmapPlateletsAvailable,
    ComplementaryPlasmaAvailable,
    EnableVistaCfr11PinLogging,
    AllowExtraWbcMessages,
    ServiceModePeriodicLog,
    SpecialBlackStampNeedle,
    PloFlag,
    PloPcaFlag,
    ShowPlasmaVolume,
    ExtraPlasmaNoAc,
    JapanFeatures,
    AllowAutoConfPlasmaProcs,
    ProcedureConfirmPopup,
    ConfirmPasBagBarcodeScan,
    PIRPreferred,
    TriplePpcFlag,
FEATURE_DEF_END
};


#endif /* BOOLEANFEATURES_H_ */
