// This file is auto-generated by the build_bool_feature_init.sed utility.
//   DO NOT EDIT this file directly!

#include "software_cds.h"

void Software_CDS::booleanFeatureInit()
{
     _features[EnableScreenshotButton].feature_file_label = "enable_screenshot_button";
     _features[EnableScreenshotButton].feature_key_id = 0;
     _features[EnableScreenshotButton].permission = RND_ONLY;

     _features[ApsHighSpeedLogEnable].feature_file_label = "aps_high_speed_log_enable";
     _features[ApsHighSpeedLogEnable].feature_key_id = 1;
     _features[ApsHighSpeedLogEnable].permission = RND_ONLY;

     _features[CpsHighSpeedLogEnable].feature_file_label = "cps_high_speed_log_enable";
     _features[CpsHighSpeedLogEnable].feature_key_id = 2;
     _features[CpsHighSpeedLogEnable].permission = RND_ONLY;

     _features[SelectScreenDisplayPlateletVolume].feature_file_label = "select_screen_display_platelet_volume";
     _features[SelectScreenDisplayPlateletVolume].feature_key_id = 4;
     _features[SelectScreenDisplayPlateletVolume].permission = SERVICE;

     _features[AllowAdjustFlowRatesOnProcedureSelect].feature_file_label = "allow_adjust_flow_rates_on_procedure_select";
     _features[AllowAdjustFlowRatesOnProcedureSelect].feature_key_id = 5;
     _features[AllowAdjustFlowRatesOnProcedureSelect].permission = SERVICE;

     _features[ConfirmAcConnection].feature_file_label = "confirm_ac_connection";
     _features[ConfirmAcConnection].feature_key_id = 6;
     _features[ConfirmAcConnection].permission = SERVICE;

     _features[DisplayResidualVolumes].feature_file_label = "display_residual_volumes";
     _features[DisplayResidualVolumes].feature_key_id = 8;
     _features[DisplayResidualVolumes].permission = SERVICE;

     _features[PostcountPlateletMobilizationAlgorithm].feature_file_label = "postcount_platelet_mobilization_algorithm";
     _features[PostcountPlateletMobilizationAlgorithm].feature_key_id = 9;
     _features[PostcountPlateletMobilizationAlgorithm].permission = SERVICE;

     _features[AiroutMitigation].feature_file_label = "airout_mitigation";
     _features[AiroutMitigation].feature_key_id = 10;
     _features[AiroutMitigation].permission = SERVICE;

     _features[AmapPlateletsAvailable].feature_file_label = "amap_platelets_available";
     _features[AmapPlateletsAvailable].feature_key_id = 11;
     _features[AmapPlateletsAvailable].permission = SERVICE;

     _features[ComplementaryPlasmaAvailable].feature_file_label = "complementary_plasma_available";
     _features[ComplementaryPlasmaAvailable].feature_key_id = 12;
     _features[ComplementaryPlasmaAvailable].permission = SERVICE;

     _features[EnableVistaCfr11Tracking].feature_file_label = "cfr11_pin_logging";
     _features[EnableVistaCfr11Tracking].feature_key_id = 14;
     _features[EnableVistaCfr11Tracking].permission = SERVICE;

     _features[AllowExtraWbcMessages].feature_file_label = "allow_extra_wbc_messages";
     _features[AllowExtraWbcMessages].feature_key_id = 15;
     _features[AllowExtraWbcMessages].permission = SERVICE;

     _features[ServiceModePeriodicLog].feature_file_label = "service_mode_periodic_log";
     _features[ServiceModePeriodicLog].feature_key_id = 16;
     _features[ServiceModePeriodicLog].permission = SERVICE;

     _features[SpecialBlackStampNeedle].feature_file_label = "special_black_stamp_needle";
     _features[SpecialBlackStampNeedle].feature_key_id = 20;
     _features[SpecialBlackStampNeedle].permission = SERVICE;

     _features[PloFlag].feature_file_label = "plo_flag";
     _features[PloFlag].feature_key_id = 21;
     _features[PloFlag].permission = SERVICE;

     _features[PloPcaFlag].feature_file_label = "plopca_flag";
     _features[PloPcaFlag].feature_key_id = 22;
     _features[PloPcaFlag].permission = SERVICE;

     _features[ApsAlarmDetectPosPressure].feature_file_label = "aps_alarm_detect_pos_pressure";
     _features[ApsAlarmDetectPosPressure].feature_key_id = 23;
     _features[ApsAlarmDetectPosPressure].permission = SERVICE;

     _features[ShowPlasmaVolume].feature_file_label = "show_plasma_volume";
     _features[ShowPlasmaVolume].feature_key_id = 24;
     _features[ShowPlasmaVolume].permission = SERVICE;

     _features[ExtraPlasmaNoAc].feature_file_label = "extra_plasma_no_ac";
     _features[ExtraPlasmaNoAc].feature_key_id = 25;
     _features[ExtraPlasmaNoAc].permission = SERVICE;

     _features[JapanFeatures].feature_file_label = "japan_features";
     _features[JapanFeatures].feature_key_id = 26;
     _features[JapanFeatures].permission = SERVICE;

     _features[AllowAutoConfPlasmaProcs].feature_file_label = "allow_auto_conf_plasma_procs";
     _features[AllowAutoConfPlasmaProcs].feature_key_id = 27;
     _features[AllowAutoConfPlasmaProcs].permission = SERVICE;

     _features[ProcedureConfirmPopup].feature_file_label = "procedure_confirmation_popup";
     _features[ProcedureConfirmPopup].feature_key_id = 28;
     _features[ProcedureConfirmPopup].permission = SERVICE;

     _features[ConfirmPasBagBarcodeScan].feature_file_label = "confirm_pas_bag_barcode_scan";
     _features[ConfirmPasBagBarcodeScan].feature_key_id = 29;
     _features[ConfirmPasBagBarcodeScan].permission = SERVICE;

     _features[PIRPreferred].feature_file_label = "pir_preferred";
     _features[PIRPreferred].feature_key_id = 30;
     _features[PIRPreferred].permission = SERVICE;

     _features[TriplePpcFlag].feature_file_label = "triple_ppc_flag";
     _features[TriplePpcFlag].feature_key_id = 31;
     _features[TriplePpcFlag].permission = SERVICE;

}

