// This file is auto-generated by the build_value_feature_init.sed utility.
//   DO NOT EDIT this file directly!

#include "software_cds.h"

void Software_CDS::valueFeatureInit()
{
     _valueFeatures[VistaIP].feature_file_label = "vista_ip_address";
     _valueFeatures[VistaIP].feature_key_id = 0;
     _valueFeatures[VistaIP].permission = SERVICE;

     _valueFeatures[VistaPort].feature_file_label = "vista_port";
     _valueFeatures[VistaPort].feature_key_id = 1;
     _valueFeatures[VistaPort].permission = SERVICE;

     _valueFeatures[PlasmaLadderMin].feature_file_label = "plasma_ladder_min";
     _valueFeatures[PlasmaLadderMin].feature_key_id = 2;
     _valueFeatures[PlasmaLadderMin].permission = SERVICE;

     _valueFeatures[PlasmaLadderMax].feature_file_label = "plasma_ladder_max";
     _valueFeatures[PlasmaLadderMax].feature_key_id = 3;
     _valueFeatures[PlasmaLadderMax].permission = SERVICE;

     _valueFeatures[PPCConcLow].feature_file_label = "ppc_conc_low";
     _valueFeatures[PPCConcLow].feature_key_id = 4;
     _valueFeatures[PPCConcLow].permission = SERVICE;

     _valueFeatures[PPCConcHigh].feature_file_label = "ppc_conc_high";
     _valueFeatures[PPCConcHigh].feature_key_id = 5;
     _valueFeatures[PPCConcHigh].permission = SERVICE;

     _valueFeatures[StandardConcLow].feature_file_label = "standard_conc_low";
     _valueFeatures[StandardConcLow].feature_key_id = 6;
     _valueFeatures[StandardConcLow].permission = SERVICE;

     _valueFeatures[StandardConcHigh].feature_file_label = "standard_conc_high";
     _valueFeatures[StandardConcHigh].feature_key_id = 7;
     _valueFeatures[StandardConcHigh].permission = SERVICE;

}

