# $Header: E:/BCT_Development/Trima5.R/Trima/unit_test/gui/rcs/makefile.vx 1.15 2009/08/03 17:15:06Z dslausb Exp dslausb $
#
# Makefile - makefile for the gui unit_test
#

ifeq ($(BUILD_TYPE),CLEAN)
.PHONY: all
all: clean
else
.PHONY: all
all: check_opt_change libs app

ifneq ($(SIMDIR),)
all += copy
endif

endif

#
# Define location for unicode stuff
#
UNICODEDIR = $(COMDIR)/unicode_string
MAINDIR = ..\..

#
# Local overrides - must be defined before including makefile.vxc
#
ADDN_INCDIR = $(addprefix -I, h $(UNICODEDIR) $(addprefix $(MAINDIR)/, trima_common cds gui gui\unicode_string proc\interface proc\algorithm))
ADDN_LDFLAGS =
ADDN_CXXFLAGS =

#
# MAINDIR should be set to the relative path from this makefile directory
# to the base trima project directory.  MAINDIR must use \ (DOS/Windows
# style) directory separators if they are needed.
#
vpath %.cpp utility:routines/l10n:routines/manuals:delay:respond:touch:alarm:snap
#vpath %.o utility:routines/l10n:routines/manuals:delay:respond:touch:alarm:snap

include $(MAINDIR)/makefile.vxc

#
# Define location for Trima libraries
#
LIBDIR = $(MAINDIR)/lib

.PHONY: libs
libs:
        @cd $(MAINDIR)\trima_common && $(MAKE) -f makefile.vx CPU=$(CPU) BUILD_TYPE=$(BUILD_TYPE) COMDIR=$(COMDIR)

#
# The following should define all of the source files of each type
# to be compiled for the executable
#
APP_NAME := simUtils
simUtils_dir = ..\bin
simUtils_c_files   = 
simUtils_cxx_files = \
	utility/simUtilities.cpp utility/simMsgSys.cpp utility/simRoutineBase.cpp	\
	utility/simActionQueue.cpp utility/simScreenCount.cpp				\
	routines/l10n/simConfig.cpp  routines/l10n/fullRoutine.cpp			\
	routines/manuals/manualShotsNav.cpp routines/manuals/manualShots.cpp		\
	routines/manuals/baseShots.cpp							\
	delay/simDelay.cpp respond/simResponder.cpp touch/simScreenTouch.cpp		\
	alarm/simAlarms.cpp snap/simScreenCapture.cpp
        
simUtils_libs = $(LIBDIR)\libtrima_common.a $(LIBDIR)\libproc_interface.a
simUtils_lib_list =
include $(MAINDIR)/makefile.process_app

#
#
# This is the standard makefile for Trima applications
#
app : $(APP_LIST)
include $(MAINDIR)/makefile.build_apps

.phony: copy
copy: $(APP_LIST) $(subst /,\, $(SIMDIR))\source\unit_test\bin\simUtils.out

$(subst /,\, $(SIMDIR))\source\unit_test\bin\simUtils.out: ..\bin\simUtils.out
	@xcopy /Y /R /F /I ..\bin\simUtils.out $(subst /,\, $(SIMDIR))\source\unit_test\bin
