# $Header$
#
# Makefile - makefile for the predict unit_test
#
# $Log$
#

ifeq ($(BUILD_TYPE),CLEAN)
.PHONY: all
all: clean
else
.PHONY: all
all: check_opt_change libs app
endif

#
# Local overrides - must be defined before including makefile.vxc
#
ADDN_INCDIR = -I ..\..\trima_common -I..\..\cds -I..\..\proc\algorithm -I..\..\proc\interface
ADDN_LDFLAGS =
ADDN_CXXFLAGS =

#
# MAINDIR should be set to the relative path from this makefile directory
# to the base trima project directory.  MAINDIR must use \ (DOS/Windows
# style) directory separators if they are needed.
#
MAINDIR = ..\..
include $(MAINDIR)/makefile.vxc

#
# Define location for Trima libraries
#
LIBDIR = $(MAINDIR)/lib

.PHONY: libs
libs:
	@cd $(MAINDIR)\trima_common && $(MAKE) -f makefile.vx CPU=$(CPU) BUILD_TYPE=$(BUILD_TYPE) COMDIR=$(COMDIR)

#
# The following should define all of the source files of each type
# to be compiled for the executable
#
APP_NAME := predict_test
predict_test_dir = ..\bin
predict_test_c_files   = 
predict_test_cxx_files = predict_test.cpp
predict_test_libs = $(LIBDIR)\libtrima_common.a $(LIBDIR)\libproc_algorithm.a $(LIBDIR)\libproc_interface.a
predict_test_lib_list =
include $(MAINDIR)/makefile.process_app

#
# This is the standard makefile for Trima applications
#
app : $(APP_LIST)
include $(MAINDIR)/makefile.build_apps


