/*******************************************************************************
 *
 * Copyright (c) 2009 by CaridianBCT, Inc.  All rights reserved.
 *
 * TITLE:      simScreenshotCycleNames.hpp
 *
 * AUTHOR:     Dan Slauson
 *
 * DESCRIPTION: This file contains some structs containing screenshot info
 *
 *******************************************************************************/

#include "guiUnitTestMessageDefs.h"
#include "simScreenshotLabels.hpp"

typedef struct
{
	const int id;
	const char* name;
	unsigned int options;
} SCREENSHOTINFO;

enum
{
	SHOT_OPTS_DEFAULT=0,
	SHOT_OPTS_NO_MAPPING=1,
	SHOT_OPTS_NO_PRUNING=2,
	SHOT_OPTS_LBL_JAPAN_ONLY=4,
	SHOT_OPTS_LBL_EVERYONE_BUT_JAPAN=8,
	SHOT_OPTS_LBL_VISTA_ONLY=16,
	SHOT_OPTS_LBL_INCORRECT=32,
	SHOT_OPTS_LBL_AAS_ONLY=64,
	SHOT_OPTS_NO_LABELING=128
};


static SCREENSHOTINFO AAS_RUNSUM_SCREENSHOT_INFO[] =
{
	{ AAS_RUNSUM_PTF_SRBC_SALVAGE_BOTH,		"AasRunSummPtfSrbcSalvageBoth",		SHOT_OPTS_LBL_AAS_ONLY },
	{ AAS_RUNSUM_PTF_DRBC_SALVAGE_RAS,		"AasRunSummPtfDrbcSalvageRas",		SHOT_OPTS_LBL_AAS_ONLY },
	{ AAS_RUNSUM_PTF_SRBC_SALVAGE_RAS,		"AasRunSummPtfSrbcSalvageRas",		SHOT_OPTS_LBL_AAS_ONLY | SHOT_OPTS_NO_PRUNING},
	{ AAS_RUNSUM_PTF_SRBC_SALVAGE_PAS,		"AasRunSummPtfSrbcSalvagePas",		SHOT_OPTS_LBL_AAS_ONLY | SHOT_OPTS_NO_PRUNING},
	{ AAS_RUNSUM_NON_PTF_SALVAGE_PAS,		"AasRunSummNonPtfSalvagePas",		SHOT_OPTS_LBL_AAS_ONLY | SHOT_OPTS_NO_PRUNING},
	{ AAS_RUNSUM_PTF_DRBC_NON_SALVAGE,		"AasRunSummPtfDrbcNonSalvage",		SHOT_OPTS_LBL_AAS_ONLY | SHOT_OPTS_NO_PRUNING},
	{ AAS_RUNSUM_PTF_SRBC_NON_SALVAGE,		"AasRunSummPtfSrbcNonSalvage",		SHOT_OPTS_LBL_AAS_ONLY | SHOT_OPTS_NO_PRUNING},
	{ AAS_RUNSUM_INST_DRBC_ABOVE,			"AasRunSummInstDrbcAbove",			SHOT_OPTS_LBL_AAS_ONLY },
	{ AAS_RUNSUM_INST_DRBC_BELOW,			"AasRunSummInstDrbcBelow",			SHOT_OPTS_LBL_AAS_ONLY },
	{ AAS_RUNSUM_INST_SRBC_BELOW,			"AasRunSummInstSrbcBelow",			SHOT_OPTS_LBL_AAS_ONLY },
	{ AAS_RUNSUM_INST_SRBC_ABOVE_WITH_PAS,	"AasRunSummInstSrbcAboveWithPas",	SHOT_OPTS_LBL_AAS_ONLY },
	{ AAS_RUNSUM_INST_SRBC_ABOVE,			"AasRunSummInstSrbcAbove",			SHOT_OPTS_LBL_AAS_ONLY },
	{ AAS_RUNSUM_INST_NO_SEAL,            	"AasRunSummInstNoSeal",				SHOT_OPTS_LBL_AAS_ONLY | SHOT_OPTS_NO_PRUNING}
};

static SCREENSHOTINFO RAS_CONNECT_SCREENSHOT_INFO[] =
{
	{ RAS_CONNECT_TYPE_TWO_BAG_SET_TWO_BAGS_NEEDED,	"RasConnectDrbcSetDouble",	SHOT_OPTS_LBL_AAS_ONLY },
	{ RAS_CONNECT_TYPE_TWO_BAG_SET_ONE_BAG_NEEDED,	"RasConnectDrbcSetSingle",	SHOT_OPTS_LBL_AAS_ONLY },
	{ RAS_CONNECT_TYPE_ONE_BAG_SET,					"RasConnectSrbcSet",		SHOT_OPTS_LBL_AAS_ONLY }
};

static SCREENSHOTINFO ABORT_TYPE_SCREENSHOT_INFO[] =
{
	{ ABORT_CONFIRM_NORMAL,				"AbortConfirmNormal",			SHOT_OPTS_DEFAULT },
	{ ABORT_CONFIRM_AAS_NORMAL,			"AbortConfirmAasNormal",		SHOT_OPTS_LBL_AAS_ONLY },
	{ ABORT_CONFIRM_AAS_WITH_END_RAS,	"AbortConfirmAasWithEndRas",	SHOT_OPTS_LBL_AAS_ONLY },
	{ ABORT_CONFIRM_AAS_WITH_END_PAS,	"AbortConfirmAasWithEndPas",	SHOT_OPTS_LBL_AAS_ONLY },
	{ ABORT_CONFIRM_AAS_WITH_END_ANY,	"AbortConfirmAasWithEndAny",	SHOT_OPTS_LBL_AAS_ONLY },
	{ ABORT_CONFIRM_RINSEBACK,			"AbortConfirmRinseback",		SHOT_OPTS_DEFAULT },
	{ ABORT_CONFIRM_SPILLOVER,			"AbortConfirmSpillover",		SHOT_OPTS_DEFAULT },
	{ ABORT_CONFIRM_AIR_IN_PLASMA,		"AbortConfirmAirInPlasma",		SHOT_OPTS_DEFAULT }
};

static SCREENSHOTINFO CHANNEL_CLAMP_SCREENSHOT_INFO[] =
{
	{ CHANNEL_CLAMP_WHITE_RAS,	"ChannelClampWhiteRas",		SHOT_OPTS_LBL_AAS_ONLY },
	{ CHANNEL_CLAMP_WHITE_PAS,	"ChannelClampWhitePas",		SHOT_OPTS_LBL_AAS_ONLY },
	{ CHANNEL_CLAMP_WHITE_BOTH,	"ChannelClampWhiteBoth",	SHOT_OPTS_LBL_AAS_ONLY },
	{ CHANNEL_CLAMP_BLACK,		"ChannelClampBlack",		SHOT_OPTS_LBL_AAS_ONLY }
};

static SCREENSHOTINFO MSS_END_SCREENSHOT_INFO[] =
{
	{ MSS_END_WHITE_RAS_SEAL,	"MssEndWhiteRasSeal",	SHOT_OPTS_LBL_AAS_ONLY },
	{ MSS_END_WHITE_RAS_REMOVE,	"MssEndWhiteRasRemove",	SHOT_OPTS_LBL_AAS_ONLY },
	{ MSS_END_WHITE_PAS_SEAL,	"MssEndWhitePasSeal",	SHOT_OPTS_LBL_AAS_ONLY },
	{ MSS_END_WHITE_PAS_REMOVE,	"MssEndWhitePasRemove",	SHOT_OPTS_LBL_AAS_ONLY | SHOT_OPTS_NO_PRUNING},
	{ MSS_END_WHITE_BOTH_SEAL,	"MssEndWhiteBothSeal",	SHOT_OPTS_LBL_AAS_ONLY | SHOT_OPTS_NO_PRUNING},
	{ MSS_END_WHITE_BOTH_REMOVE,"MssEndWhiteBothRemove",SHOT_OPTS_LBL_AAS_ONLY | SHOT_OPTS_NO_PRUNING},
	{ MSS_END_BLACK_SEAL,		"MssEndBlackSeal",		SHOT_OPTS_LBL_AAS_ONLY | SHOT_OPTS_NO_PRUNING},
	{ MSS_END_BLACK_REMOVE,		"MssEndBlackRemove",	SHOT_OPTS_LBL_AAS_ONLY | SHOT_OPTS_NO_PRUNING}
};

static SCREENSHOTINFO RS1_SCREENSHOT_INFO[] =
{
	{ RS1_DISPLAY_TYPE_NO_FRILLS,								"Rs1NoFrills",							SHOT_OPTS_DEFAULT | SHOT_OPTS_NO_PRUNING },
	{ RS1_DISPLAY_TYPE_RESIDUALS,								"Rs1Residuals",							SHOT_OPTS_DEFAULT | SHOT_OPTS_NO_PRUNING},
	{ RS1_DISPLAY_TYPE_PLASMA_RINSEBACK,						"Rs1PlasmaRinseback",					SHOT_OPTS_LBL_JAPAN_ONLY | SHOT_OPTS_NO_PRUNING },
	{ RS1_DISPLAY_TYPE_SALINE_RINSEBACK,						"Rs1SalineRinseback",					SHOT_OPTS_LBL_JAPAN_ONLY | SHOT_OPTS_NO_PRUNING },
	{ RS1_DISPLAY_TYPE_AAS_TIME,								"Rs1AasTime",							SHOT_OPTS_LBL_AAS_ONLY | SHOT_OPTS_NO_PRUNING},
	{ RS1_DISPLAY_TYPE_AAS_TIME_AND_PLASMA_RINSEBACK,			"Rs1AasTimeAndPlasmaRinseback",			SHOT_OPTS_LBL_AAS_ONLY },
	{ RS1_DISPLAY_TYPE_AAS_TIME_AND_SALINE_RINSEBACK,			"Rs1AasTimeAndSalineRinseback",			SHOT_OPTS_LBL_AAS_ONLY },
	{ RS1_DISPLAY_TYPE_AVG_INLET_AND_PLASMA_RINSEBACK,			"Rs1AvgInletAndPlasmaRinseback",		SHOT_OPTS_LBL_JAPAN_ONLY },
	{ RS1_DISPLAY_TYPE_AVG_INLET_AND_SALINE_RINSEBACK,			"Rs1AvgInletAndSalineRinseback",		SHOT_OPTS_LBL_JAPAN_ONLY },
	{ RS1_DISPLAY_TYPE_AVG_INLET_AND_AAS_TIME,					"Rs1AvgInletAndAasTime",				SHOT_OPTS_LBL_JAPAN_ONLY | SHOT_OPTS_NO_PRUNING},
	{ RS1_DISPLAY_TYPE_RESIDUALS_AND_AAS_TIME,					"Rs1ResidualsAndAasTime",				SHOT_OPTS_LBL_AAS_ONLY | SHOT_OPTS_NO_PRUNING},
	{ RS1_DISPLAY_TYPE_RESIDUALS_AND_INLET,						"Rs1ResidualsAndInlet",					SHOT_OPTS_LBL_JAPAN_ONLY | SHOT_OPTS_NO_PRUNING},
	{ RS1_DISPLAY_TYPE_AAS_TIME_AND_INLET,						"Rs1AasTimeAndInlet",					SHOT_OPTS_LBL_JAPAN_ONLY | SHOT_OPTS_NO_PRUNING},
	{ RS1_DISPLAY_TYPE_AAS_TIME_AND_INLET_AND_PLASMA_RINSEBACK,	"Rs1AasTimeAndInletAndPlasmaRinseback",	SHOT_OPTS_LBL_JAPAN_ONLY | SHOT_OPTS_NO_PRUNING},
	{ RS1_DISPLAY_TYPE_AAS_TIME_AND_INLET_AND_SALINE_RINSEBACK,	"Rs1AasTimeAndInletAndSalineRinseback",	SHOT_OPTS_LBL_JAPAN_ONLY | SHOT_OPTS_NO_PRUNING},
	{ RS1_DISPLAY_TYPE_AVG_INLET,								"Rs1AvgInlet",							SHOT_OPTS_LBL_JAPAN_ONLY | SHOT_OPTS_NO_PRUNING },
	{ RS1_DISPLAY_TYPE_AAS_TIME_AND_INLET_AND_RESIDUALS,		"Rs1AasTimeAndInletAndResiduals",		SHOT_OPTS_LBL_JAPAN_ONLY | SHOT_OPTS_NO_PRUNING}
};

static SCREENSHOTINFO SYSDISP_SCREENSHOT_INFO[] =
{
	{ SYSDISP_CASSETTE_LOWERING,		"sysDispLowering",		SHOT_OPTS_DEFAULT },
	{ SYSDISP_CASSETTE_LOWERED,			"sysDispLowered",		SHOT_OPTS_DEFAULT | SHOT_OPTS_NO_PRUNING},
	{ SYSDISP_CASSETTE_EVACUATING,		"sysDispEvac",			SHOT_OPTS_DEFAULT },
	{ SYSDISP_CASSETTE_RAISING,			"sysDispRaising",		SHOT_OPTS_DEFAULT },
	{ SYSDISP_CASSETTE_RAISED,			"sysDispRaised",		SHOT_OPTS_DEFAULT | SHOT_OPTS_NO_PRUNING},
	{ SYSDISP_CASSETTE_DONT_CONNECT_AC,	"sysDispDontConnectAc",	SHOT_OPTS_LBL_JAPAN_ONLY | SHOT_OPTS_NO_PRUNING},
	{ SYSDISP_CLAMP_SAMPLE_BAG,			"clampSampleBag",		SHOT_OPTS_LBL_EVERYONE_BUT_JAPAN },
	{ SYSDISP_CLAMP_SAMPLE_BAG_JP,		"clampSampleBagJp",		SHOT_OPTS_LBL_JAPAN_ONLY | SHOT_OPTS_NO_PRUNING},
	{ SYSDISP_CLAMP_PAS,				"clampPas",				SHOT_OPTS_LBL_EVERYONE_BUT_JAPAN },
	{ SYSDISP_CLAMP_PAS_JP,				"clampPasJp",			SHOT_OPTS_LBL_JAPAN_ONLY | SHOT_OPTS_NO_PRUNING}
};

static SCREENSHOTINFO PTF_LOAD_SCREENSHOT_INFO[] =
{
	{ PTF_LOAD_WHITE_RAS,		"rbcSetupWhiteRas",		SHOT_OPTS_LBL_EVERYONE_BUT_JAPAN },
	{ PTF_LOAD_WHITE_BOTH,		"rbcSetupWhiteBoth",	SHOT_OPTS_LBL_EVERYONE_BUT_JAPAN | SHOT_OPTS_NO_PRUNING},
	{ PTF_LOAD_BLACK_RAS,		"rbcSetupBlackRas",		SHOT_OPTS_LBL_EVERYONE_BUT_JAPAN | SHOT_OPTS_NO_PRUNING},
	{ PTF_LOAD_WHITE_RAS_JP,	"rbcSetupWhiteRasJp",	SHOT_OPTS_LBL_JAPAN_ONLY | SHOT_OPTS_NO_PRUNING},
	{ PTF_LOAD_WHITE_BOTH_JP,	"rbcSetupWhiteBothJp",	SHOT_OPTS_LBL_JAPAN_ONLY | SHOT_OPTS_NO_PRUNING},
	{ PTF_LOAD_BLACK_RAS_JP,	"rbcSetupBlackRasJp",	SHOT_OPTS_LBL_JAPAN_ONLY | SHOT_OPTS_NO_PRUNING}
};

static SCREENSHOTINFO DON_CONN_SCREENSHOT_INFO[] =
{
	{ DON_CONN_DIVERSION_OFF,	"donConnDiversionOff",	SHOT_OPTS_LBL_EVERYONE_BUT_JAPAN },
	{ DON_CONN_DIVERSION_ON,	"donConnDiversionOn",	SHOT_OPTS_LBL_EVERYONE_BUT_JAPAN },
	{ DON_CONN_DIVERSION_OFF_JP,"donConnDiversionOffJp",SHOT_OPTS_LBL_JAPAN_ONLY },
	{ DON_CONN_DIVERSION_ON_JP,	"donConnDiversionOnJp",	SHOT_OPTS_LBL_JAPAN_ONLY }
};

static SCREENSHOTINFO PAS_CONNECT_SCREENSHOT_INFO[] =
{
	{ PAS_CONNECT_TYPE_OVERRIDE_ON,	"pasConnectOverrideOn",	SHOT_OPTS_LBL_AAS_ONLY },
	{ PAS_CONNECT_TYPE_OVERRIDE_OFF,"pasConnectOverrideOff",SHOT_OPTS_LBL_AAS_ONLY }
};

static SCREENSHOTINFO DRBC_SPLIT_SCREENSHOT_INFO[] =
{
	{ DRBC_SPLIT_COLLECT_FILTERED,		"drbcSplitCollectFiltered",		SHOT_OPTS_DEFAULT },
	{ DRBC_SPLIT_COLLECT_NONFILTERED,	"drbcSplitCollectNonFiltered",	SHOT_OPTS_DEFAULT },
	{ DRBC_SPLIT_RAS_ADDITION,			"drbcSplitRasAddition",			SHOT_OPTS_DEFAULT }
};

static SCREENSHOTINFO RS2_SCREENSHOT_INFO[] =
{
	{ RS2_DRBC,	"Drbc",	SHOT_OPTS_DEFAULT },
	{ RS2_SRBC,	"Srbc",	SHOT_OPTS_DEFAULT | SHOT_OPTS_NO_PRUNING}
};

static SCREENSHOTINFO PAS_INIT_SPLIT_SCREENSHOT_INFO[] =
{
	{ PAS_INIT_SPLIT_NORMAL,"pasInitSplit",		SHOT_OPTS_LBL_EVERYONE_BUT_JAPAN },
	{ PAS_INIT_SPLIT_JP,	"pasInitSplitJp",	SHOT_OPTS_LBL_JAPAN_ONLY }
};

static SCREENSHOTINFO SYSCLAMP_SCREENSHOT_INFO[] =
{
	{ SYSCLAMP_KEY_AIR_REMOVAL,		"SysClampAirRemoval",		SHOT_OPTS_LBL_EVERYONE_BUT_JAPAN },
	{ SYSCLAMP_NO_AIR_REMOVAL,		"SysClampNoAirRemoval",		SHOT_OPTS_LBL_EVERYONE_BUT_JAPAN },
	{ SYSCLAMP_KEY_AIR_REMOVAL_JP,	"SysClampAirRemovalJp",		SHOT_OPTS_LBL_JAPAN_ONLY },
	{ SYSCLAMP_NO_AIR_REMOVAL_JP,	"SysClampNoAirRemovalJp",	SHOT_OPTS_LBL_JAPAN_ONLY | SHOT_OPTS_NO_PRUNING }
};

static SCREENSHOTINFO JPSYSCLAMP_SCREENSHOT_INFO[] =
{
	{ 0,		"SysClampPlasmaAirRemovalJp",		SHOT_OPTS_LBL_EVERYONE_BUT_JAPAN }
};

static SCREENSHOTINFO SYSDONOR_SCREENSHOT_INFO[] =
{
	{ SYSDONOR_DISPLAY_INITIAL,					"TwoButtonInitial",				SHOT_OPTS_DEFAULT },
	{ SYSDONOR_DISPLAY_VIP_DOWNLOADING,			"TwoButtonVistaDl",				SHOT_OPTS_LBL_VISTA_ONLY },
	{ SYSDONOR_DISPLAY_DONINFO_DONE,			"TwoButtonDonInfoDone",			SHOT_OPTS_DEFAULT | SHOT_OPTS_NO_PRUNING},
	{ SYSDONOR_DISPLAY_LOADSET_DONE,			"TwoButtonLoadSetDone",			SHOT_OPTS_DEFAULT | SHOT_OPTS_NO_PRUNING},
	{ SYSDONOR_DISPLAY_LOADSET_DONE_AC_PRIME,	"TwoButtonLoadSetDoneAcPrime",	SHOT_OPTS_DEFAULT },
	{ SYSDONOR_DISPLAY_BOTH_DONE,				"TwoButtonBothDone",			SHOT_OPTS_DEFAULT }
};

static SCREENSHOTINFO CONFIRM_DON_INFO_SCREENSHOT_INFO[] =
{
	{ CONFIRM_DON_INFO_VERSION_MALE,	"confirmDonorInfoMale",		SHOT_OPTS_DEFAULT },
	{ CONFIRM_DON_INFO_VERSION_FEMALE,	"confirmDonorInfoFemale",	SHOT_OPTS_DEFAULT },
	{ CONFIRM_DON_INFO_BLOOD_TYPE_OP,	"confirmDonorInfoOPos",		SHOT_OPTS_DEFAULT },
	{ CONFIRM_DON_INFO_BLOOD_TYPE_ON,	"confirmDonorInfoONeg",		SHOT_OPTS_DEFAULT | SHOT_OPTS_NO_PRUNING},
	{ CONFIRM_DON_INFO_BLOOD_TYPE_AP,	"confirmDonorInfoAPos",		SHOT_OPTS_DEFAULT },
	{ CONFIRM_DON_INFO_BLOOD_TYPE_AN,	"confirmDonorInfoANeg",		SHOT_OPTS_DEFAULT },
	{ CONFIRM_DON_INFO_BLOOD_TYPE_BP,	"confirmDonorInfoBPos",		SHOT_OPTS_DEFAULT },
	{ CONFIRM_DON_INFO_BLOOD_TYPE_BN,	"confirmDonorInfoBNeg",		SHOT_OPTS_DEFAULT },
	{ CONFIRM_DON_INFO_BLOOD_TYPE_ABP,	"confirmDonorInfoABPos",	SHOT_OPTS_DEFAULT },
	{ CONFIRM_DON_INFO_BLOOD_TYPE_ABN,	"confirmDonorInfoABNeg",	SHOT_OPTS_DEFAULT }
};

static SCREENSHOTINFO POWERDOWN_SCREENSHOT_INFO[] =
{
	{ POWERDOWN_POWERING_DOWN,		"powerdown",		SHOT_OPTS_DEFAULT },
	{ POWERDOWN_WATCHDOG_FAILURE,	"watchdogFailure",	SHOT_OPTS_DEFAULT }
};

