
#ifndef __SIM_SCREENSHOT_LABELS_HPP__
#define __SIM_SCREENSHOT_LABELS_HPP__

#define SCREENSHOT_LABEL_JAPAN_ONLY			"jp"
#define SCREENSHOT_LABEL_EVERYONE_BUT_JAPAN	"nonjp"
#define SCREENSHOT_LABEL_VISTA_ONLY			"vista"
#define SCREENSHOT_LABEL_INCORRECT			"incorrect"
#define SCREENSHOT_LABEL_AAS_ONLY			"aas"

#endif // #ifndef __SIM_SCREENSHOT_LABELS_HPP__


