//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelFill.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExcelFill.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;Windows-1252&quot;?&gt;&lt;FillSerialize xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;&lt;CurrentFillInfo&gt;&lt;Name /&gt;&lt;Color&gt;#80FF80&lt;/Color&gt;&lt;Highlight&gt;true&lt;/Highlight&gt;&lt;Hyperlink&gt;false&lt;/Hyperlink&gt;&lt;/CurrentFillInfo&gt;&lt;/FillSerialize&gt;.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap fill_48x48 {
            get {
                object obj = ResourceManager.GetObject("fill_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;customUI xmlns=&quot;http://schemas.microsoft.com/office/2006/01/customui&quot; xmlns:x=&quot;CaridianBCT&quot; onLoad=&quot;RibbonLoaded&quot; loadImage=&quot;GetImage&quot;&gt;
        ///	&lt;ribbon&gt;
        ///		&lt;tabs&gt;
        ///			&lt;tab idQ=&quot;x:Analysis&quot; label=&quot;Analysis&quot;&gt;
        ///				&lt;group id=&quot;QuickFill&quot; label=&quot;Quick Fill&quot;&gt;
        ///					&lt;button id=&quot;FillButton&quot; label=&quot;Fill&quot; image=&quot;fill-48x48.png&quot; size=&quot;large&quot; onAction=&quot;FillDefault&quot; /&gt;
        ///					&lt;button id=&quot;SettingsButton&quot; label=&quot;Settings&quot; image=&quot;settings-48x48.png&quot; size=&quot;large&quot; onAction=&quot;FillSettings&quot; /&gt;
        ///				&lt;/group&gt;
        ///			&lt;/tab&gt;	
        ///		&lt;/tabs&gt;
        ///	&lt;/ribbon&gt;
        ///&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Ribbon {
            get {
                return ResourceManager.GetString("Ribbon", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap settings_48x48 {
            get {
                object obj = ResourceManager.GetObject("settings_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.
        /// </summary>
        internal static string VersionNum {
            get {
                return ResourceManager.GetString("VersionNum", resourceCulture);
            }
        }
    }
}
